### ISSUE TITLE
OSM Web Wizard unknown url

### ISSUE THREAD

**Issue by Code-Jelle** [eclipse/sumo#10032]
I get an error when running OSM Web Wizzard.
It says the following:

  File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>

It's a URL error. Is the URL provided in the script invalid (I assume it works that way) or is something else wrong?

---

![image](https://user-images.githubusercontent.com/79859665/150794286-e57aeea1-1a47-4a94-b273-90c1514506dd.png)

SUMO-version: Where do I find that?

OS: Windows 10

**Comment by namdre** [comment]
if you open sumo-gui it shows the version number in the title bar.

**Comment by namdre** [comment]
Also, are there any more error messages if you scroll up that console window?
What are the contents of the generated scenario folder (name corresponds to the date and time at which you ran the wizard) ?

**Comment by Code-Jelle** [comment]
Hi namdre,
My version is 1.11.0.

The rest of the console is shown here:

Cannot create directory 'C:\WINDOWS\System32\2022-02-02-13-49-33'
Building scenario in 'C:\Users\jelle\Sumo\2022-02-02-13-49-33'
Downloading map data
504 Gateway Timeout 
Converting map data  
Written configuration to 'osm.netccfg'
Loading configuration ... done. 
Parsing types from 'C:\Program Files (x86)\Eclipse\Sumo\data\typemap\osmNetconvert.typ.xml' ... done.
**Error: Could not open osm-file 'osm_bbox.osm.xml'.**
Repeating initial error messages:
Could not open osm-file 'osm_bbox.osm.xml'.
**Error: No nodes loaded.**
Quitting (on error).
Written configuration to 'osm.polycfg'
Loading configuration ... done.
**Error: Could not open net-file 'osm.net.xml'.**
Quitting (on error).
Traceback (most recent call last):
File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\net\__init__.py", line 825, in readNet                            parse(gzip.open(filename), netreader)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 58, in open
binary_file = GzipFile(filename, gz_mode, compresslevel)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 174, in __init__
fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jelle\\Sumo\\2022-02-02-13-49-33\\osm.net.xml'                                                                                                                              During handling of the above exception, another exception occurred:                                                                                                                                                                             Traceback (most recent call last):
File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 487, in build
builder.build()
File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 296, in build
self.edges = sumolib.net.readNet(os.path.join(self.tmp, self.files["net"])).getEdges()
File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\net\__init__.py", line 827, in readNet
parse(filename, netreader)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\xml\sax\__init__.py", line 33, in parse                  parser.parse(source)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\xml\sax\expatreader.py", line 105, in parse
source = saxutils.prepare_input_source(source)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\xml\sax\saxutils.py", line 365, in prepare_input_source                                                                                                                          f = urllib.request.urlopen(source.getSystemId())
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
 return opener.open(url, data, timeout)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
response = self._open(req, data)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 541, in _open
return self._call_chain(self.handle_open, 'unknown',
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
result = func(*args)
File "C:\Users\jelle\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1419, in unknown_open
raise URLError('unknown url type: %s' % type)
**urllib.error.URLError: <urlopen error unknown url type: c>**                                                                                                                                                                                      Recovering
Recovering
Recovering

Hope this helps.

**Comment by namdre** [comment]
Most likely, the selected area was too large which caused the connection to the osm server to time-out:
https://stackoverflow.com/questions/36756663/prevent-504-gateway-timeout-on-overpass-api-with-piped-node-request

For alternative methods of obtaining osm data, see https://sumo.dlr.de/docs/Networks/Import/OpenStreetMapDownload.html

If you want to use osmWebWizard with a custom osm file, you can perform the following steps

1. build a smaller scenario with the desired options
2. obtain a raw osm xml file with other means

in the small scenario folder:

3. replace osm_bbox.osm.xml with your new osm file
4. run `netconvert -c osm.netccfg`
5. run `polyconvert -c osm.polycofg`
6. run build.bat
