### ISSUE TITLE
Error in osmWebWizard when I click to generate scenario.

### ISSUE THREAD

**Issue by Jbnado** [eclipse/sumo#10206]
Cannot create directory 'C:\Program Files (x86)\Eclipse\Sumo\tools\2022-02-22-14-25-54'
Building scenario in 'C:\Users\berna\Sumo\2022-02-22-14-25-54'
Downloading map data
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 487, in build
    builder.build()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 192, in build
    osmGet.get(osmArgs)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 134, in get
    readCompressed(conn, url.path, '<bbox-query n="%s" s="%s" w="%s" e="%s"/>' %
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 45, in readCompressed
    conn.request("POST", "/" + urlpath, """
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\berna\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

Recovering
Recovering
Recovering
Recovering

**Comment by namdre** [comment]
https://sumo.dlr.de/docs/FAQ.html#osmwebwizardpy_fails_to_generate_scenario_on_windows_10
