### ISSUE TITLE
xml2CSV not working in Ubuntu (SAXParseException)

### ISSUE THREAD

**Issue by zaheenSyed** [eclipse/sumo#10806]
I wanted to convert the file to csv and using the xml2csv script. I can do it in windows but in my Ubuntu OS I get the error as follows:

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
zemsyed@ZET:~/Final setup/test_lanechange_behaviour/24052022132838_krauss100\$ python3 xml2csv.py ssm_k.xml
Traceback (most recent call last):
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: no element found: line 156693, column 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xml2csv.py", line 275, in <module>
    main()
  File "xml2csv.py", line 262, in main
    attrFinder = AttrFinder(options.xsd, options.source, options.split)
  File "xml2csv.py", line 82, in __init__
    xml.sax.parse(source, self)
  File "/usr/lib/python3.8/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 127, in parse
    self.close()
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 240, in close
    self.feed("", isFinal = 1)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.8/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: ssm_k.xml:156693:7: no element found

=================================================================================================
[test_files.zip](https://github.com/eclipse/sumo/files/8765703/test_files.zip)

**Comment by namdre** [comment]
the input file is not well formed: it is lacking the closing tag `</meandata>`.
Most likely the file was copied while sumo-gui was still open. Always close the gui before processing files unless you know your parser can tolerate this.
