### ISSUE TITLE
Excecution stops after implement setPreviousSpeed function

### ISSUE THREAD

**Issue by LeonardoDelgado1905** [eclipse/sumo#10859]
I'm working with in a four intersections city. I am implementing a python script with TraCI, to modify some vehicles behaviors. At some point I had to include the function traci.vehicle.setPreviousSpeed for a type of vehicles in my simulation, but when I started the simulation, after a while I got the following that stoped the execution:

sumo-gui: ./src/microsim/MSVehicle.cpp:4472: bool MSVehicle::enterLaneAtMove(MSLane*, bool): La declaración `haveValidStopEdges()' no se cumple.

I asked in a Forum and they told me the function setPreviousSpeed was not avaliable in my sumo version (1.8.0), so I updated sumo to 1.13.0 version, I even tried to run the simulation without the types of vehicle that used the setPreviousSpeed function (so technically the function is never called) but now I have the following error (pretty similiar):

sumo-guiD: /home/leo/Descargas/sumo-1.13.0/src/microsim/MSVehicle.cpp:4931: void MSVehicle::enterLaneAtMove(MSLane*, bool): La declaración `myLaneChangeModel->isOpposite() || haveValidStopEdges()' no se cumple.
Traceback (most recent call last):
  File "/media/leo/74CA435ECA431C2C/RECOVER/LeonardoDelgado/AI-MachineLearning/AutonomosDistributed/Sumo-2x2/dim_sumo/runner.py", line 490, in <module>
    main(get_options())
  File "/media/leo/74CA435ECA431C2C/RECOVER/LeonardoDelgado/AI-MachineLearning/AutonomosDistributed/Sumo-2x2/dim_sumo/runner.py", line 483, in main
    generate_traffic_and_execute_sumo(sumoBinary, "data/out-tripinfo.xml", dNS=0.0, dWE=0.0, pNS=d, pWE=d,
  File "/media/leo/74CA435ECA431C2C/RECOVER/LeonardoDelgado/AI-MachineLearning/AutonomosDistributed/Sumo-2x2/dim_sumo/runner.py", line 357, in generate_traffic_and_execute_sumo
    density_calc, flow, vel = run(traffic_lights, trafficlights_flaws, city_size=city_size, density=density)
  File "/media/leo/74CA435ECA431C2C/RECOVER/LeonardoDelgado/AI-MachineLearning/AutonomosDistributed/Sumo-2x2/dim_sumo/runner.py", line 265, in run
    state.step(step, traffic_lights)
  File "/media/leo/74CA435ECA431C2C/RECOVER/LeonardoDelgado/AI-MachineLearning/AutonomosDistributed/Sumo-2x2/dim_sumo/Simulation.py", line 38, in step
    self.config.current_time_seconds = traci.simulation.getTime()
  File "/home/leo/Escritorio/dim_sumo/venv/lib/python3.9/site-packages/traci/_simulation.py", line 257, in getTime
    return self._getUniversal(tc.VAR_TIME)
  File "/home/leo/Escritorio/dim_sumo/venv/lib/python3.9/site-packages/traci/domain.py", line 172, in _getUniversal
    return _parse(self._retValFunc, varID, self._getCmd(varID, objectID, format, *values))
  File "/home/leo/Escritorio/dim_sumo/venv/lib/python3.9/site-packages/traci/domain.py", line 177, in _getCmd
    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)
  File "/home/leo/Escritorio/dim_sumo/venv/lib/python3.9/site-packages/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/home/leo/Escritorio/dim_sumo/venv/lib/python3.9/site-packages/traci/connection.py", line 82, in _sendExact
    if self._socket is None:
AttributeError: 'Connection' object has no attribute '_socket'

I was also working in a multiple-lane scenario and I get the same error.

I attach the  project directory 
I've been working with @cesarg39

**SUMO-version: 1.13.0**

**operating system: Debian 11**
To run the simulation execute the file "runner.py" [dim_sumo.zip](https://github.com/eclipse/sumo/files/8814893/dim_sumo.zip)

**Comment by LeonardoDelgado1905** [comment]
[traceFile.txt](https://github.com/eclipse/sumo/files/8879273/traceFile.txt)

Uploading simulation_fail.mov…

**Comment by LeonardoDelgado1905** [comment]
> The failing assertion is only active with the debug build of SUMO. For machine learning purposes, it is recommend to use the much faster release build (which will not trigger this assertion).
> 
> Nevertheless, the assertion may indicate a serious problem which I would like to investigate. Please provide a problem run in the form of a traci-traceFile and only include all simulation files loaded in this trace: https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands also, set option `traceGetters=False` to reduce the trace file size.

Hi namdre, we made the TraceFile and thats the file we are attaching. Additionally, we upload a video when we can see how it stops the excecution.

https://user-images.githubusercontent.com/38956777/173078996-7bda5802-f511-4d2a-a916-64b3d386541a.mov
[traceFile.txt](https://github.com/eclipse/sumo/files/8879363/traceFile.txt)
