### ISSUE TITLE
'TeeFile' object has no attribute 'f_lineno'

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#11257]
you currently cannot use sumolib.TeeFile to print stacktraces to
```
Process Process-1:
Traceback (most recent call last):
  File "/home/behr_mi/tsc/assign.py", line 385, in run_subnet
    traceback.print_stack(sys.stdout)
  File "/usr/lib/python3.8/traceback.py", line 190, in print_stack
    print_list(extract_stack(f, limit=limit), file=file)
  File "/usr/lib/python3.8/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/usr/lib/python3.8/traceback.py", line 347, in extract
    for f, lineno in frame_gen:
  File "/usr/lib/python3.8/traceback.py", line 301, in walk_stack
    yield f, f.f_lineno
AttributeError: 'TeeFile' object has no attribute 'f_lineno'
```

**Comment by behrisch** [comment]
maybe we can implement something along the lines of https://github.com/getsentry/raven-python/commit/4c3b7eee56246fb3bb5118879171a59806b730fb

**Comment by behrisch** [comment]
The usage of print_stack was wrong. It should be `print_stack(file=t)`.
