### ISSUE TITLE
plot_net_dump.py throwing error when closing figure window

### ISSUE THREAD

**Issue by DFazekas** [eclipse/sumo#11280]
I'm trying to generate an image illustrating edge density during the entire period of the simulation.
In running the following command, a figure is displayed (I'd rather it just create it instead of showing, but whatever). 
```bash
python "C:\Program Files (x86)\Eclipse\Sumo\tools\visualization\plot_net_dump.py" -n ./config/data/network.net.xml -i ./output/data/edgeData_vehs.xml -m density,density --internal --output ./image.png
```
But in closing the figure window, an error occurs. Here's the traceback:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\visualization\plot_net_dump.py", line 267, in <module>
    sys.exit(main(sys.argv))
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\visualization\plot_net_dump.py", line 261, in main
    helpers.closeFigure(fig, ax, options, False, expandedOutputNames)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\visualization\helpers.py", line 266, 
in closeFigure
    fig.clf()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\figure.py", line 988, in clf
    return self.clear(keep_observers=keep_observers)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\figure.py", line 2806, in clear
    super().clear(keep_observers=keep_observers)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\figure.py", line 957, in clear
    self.delaxes(ax)  # Remove ax from self._axstack.
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\figure.py", line 925, in delaxes
    self._axobservers.process("_axes_change_event", self)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\cbook\__init__.py", line 292, in process
    self.exception_handler(exc)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\cbook\__init__.py", line 96, in _exception_printer
    raise exc
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\figure.py", line 2921, in <lambda>
    self._axobservers.connect("_axes_change_event", lambda arg: func(arg))
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backend_bases.py", line 2799, in notify_axes_change
    self.toolbar.update()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backend_bases.py", line 3302, in update
    self.set_history_buttons()
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\backends\_backend_tk.py", line 738, in set_history_buttons
    self._buttons['Back']['state'] = state_map[can_back]
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1686, in __setitem__
    self.configure({key: value})
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\thoma\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2"
```

My dump file only has a single interval.

**SUMO-version:**
Version 1.14.1

**operating system:**
Windows 10

**Comment by m-kro** [comment]
Thank you for reporting!
