### ISSUE TITLE
Unable to generate scenario using osmweb wizard 

### ISSUE THREAD

**Issue by Yangdujuan** [eclipse/sumo#11716]
Hi,
when I run the osmWebWizard.py, it stops before opening sumo-gui and gives an error. Any suggestion on how to fix it?

SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired
for your information, I copy it here:
Building scenario in 'C:\Users\bwdyang\Sumo\2022-09-27-17-05-06'
Downloading map data
#Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 497, in build
    builder.build()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 196, in build
    osmGet.get(osmArgs)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 206, in get
    readCompressed(conn, url.path, '<bbox-query n="%s" s="%s" w="%s" e="%s"/>' %
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 108, in readCompressed
    conn.request("POST", "/" + urlpath, """
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Users\bwdyang\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)#
*If possible, upload an example that shows your problem.*

**SUMO-version:1.14.1

**operating system: windows 10

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#osmwebwizardpy_fails_to_generate_scenario_on_windows_10

**Comment by Yangdujuan** [comment]
Thanks! It works after installing the certificate.
