### ISSUE TITLE
SUMO SIGSEGV on three-way intersection

### ISSUE THREAD

**Issue by jjyyxx** [eclipse/sumo#12063]
When experimenting SUMO with some RL workload using libsumo, I met a SIGSEGV, and the whole program crashed (RL is good at fuzz testing :rofl:). I managed to boil down the crash to a python script generated from the `traceFile` feature. I tried to debug with a libsumo debug build at ae50a396c957cff05c40a095a10a3b9178bf7e62 using gdb, and shows the following stacktrace
```
python: /home/user/repository/sumo/src/microsim/MSVehicle.cpp:4635: double MSVehicle::getBackPositionOnLane(const MSLane*, bool) const: Assertion `myFurtherLanes.size() > 0' failed.

Thread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350457152) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) where
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350457152) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350457152) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350457152, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7cc2476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7ca87f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7ca871b in __assert_fail_base (fmt=0x7ffff7e5d150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff595703b "myFurtherLanes.size() > 0", 
    file=0x7ffff5956430 "/home/user/repository/sumo/src/microsim/MSVehicle.cpp", line=4635, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff7cb9e96 in __GI___assert_fail (assertion=0x7ffff595703b "myFurtherLanes.size() > 0", file=0x7ffff5956430 "/home/user/repository/sumo/src/microsim/MSVehicle.cpp", line=4635, 
    function=0x7ffff5956ff8 "double MSVehicle::getBackPositionOnLane(const MSLane*, bool) const") at ./assert/assert.c:101
#7  0x00007ffff541617a in MSVehicle::getBackPositionOnLane (this=0x555555eb9830, lane=0x5555566b4a20, calledByGetPosition=false) at /home/user/repository/sumo/src/microsim/MSVehicle.cpp:4635
#8  0x00007ffff5426966 in MSVehicle::getBackPositionOnLane (this=0x555555eb9830, lane=0x5555566b4a20) at /home/user/repository/sumo/src/microsim/MSVehicle.h:402
#9  0x00007ffff536bebf in MSLaneChangerSublane::getLeaders (this=0x555555e81800, target=..., vehicle=0x555555ebbc60) at /home/user/repository/sumo/src/microsim/MSLaneChangerSublane.cpp:627
#10 0x00007ffff53696b0 in MSLaneChangerSublane::change (this=0x555555e81800) at /home/user/repository/sumo/src/microsim/MSLaneChangerSublane.cpp:172
#11 0x00007ffff535a708 in MSLaneChanger::laneChange (this=0x555555e81800, t=30100) at /home/user/repository/sumo/src/microsim/MSLaneChanger.cpp:149
#12 0x00007ffff52c440e in MSEdge::changeLanes (this=0x5555566b2c60, t=30100) at /home/user/repository/sumo/src/microsim/MSEdge.cpp:792
#13 0x00007ffff52dab31 in MSEdgeControl::changeLanes (this=0x555555e845c0, t=30100) at /home/user/repository/sumo/src/microsim/MSEdgeControl.cpp:287
#14 0x00007ffff538a5ea in MSNet::simulationStep (this=0x555555ea6940) at /home/user/repository/sumo/src/microsim/MSNet.cpp:734
#15 0x00007ffff4e5ddae in libsumo::Simulation::step (time=0) at /home/user/repository/sumo/src/libsumo/Simulation.cpp:136
```
which I believe, maybe a SUMO bug. Due to my insufficient knowledge of SUMO internals, I could not dig further.

The sumocfg and other files and the trace file are attached here [cross.tar.gz](https://github.com/eclipse/sumo/files/10023847/cross.tar.gz), which could reproduce this issue on 1.15.0 and master.

Empirically, this error happens only with three-way intersections, as previous experiments targeting four-way intersection never meets such error.

**SUMO-version:** 1.15.0 & master (ae50a396c957cff05c40a095a10a3b9178bf7e62)

**operating system:** Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64)

**Comment by namdre** [comment]
Thanks for the well-prepared error inputs!

**Comment by namdre** [comment]
After, #12065, I cannot reproduce the original crash any more. Can you please give feedback from a larger set of simulations.

**Comment by jjyyxx** [comment]
Thank you, @namdre! Helpful as always.

I could not reproduce this SIGSEGV within several million iterations, so I believe this issue is fixed. May I ask if it's possible to release a patch version `1.15.1` (like `1.14.1`) in recent days? I could build the binary, but not all my coworkers feel it convenient. Otherwise, we could workaround by limiting max number of lanes to be 2 to avoid parallel connections, until `1.16.0` is released.
