### ISSUE TITLE
Max recursion error Traci

### ISSUE THREAD

**Issue by jmlouw** [eclipse/sumo#12198]
After starting and closing SUMO with Traci multiple times I'm getting this error. It seems that some list in Traci doesn't get cleared and becomes to long. it then throws this `RecursionError: maximum recursion depth exceeded in comparison`? Any idea why this is happening?

```
Traceback (most recent call last):
  File "ga.py", line 365, in <module>
    main(parse_cfg())
  File "/usr/local/lib/python3.8/dist-packages/llama/utils.py", line 164, in wrapper_validate
    return func(*args, **kwargs)
  File "ga.py", line 318, in main
    best_parent, score = ga.evolve()
  File "/usr/local/lib/python3.8/dist-packages/llama/rl/agents/ga/genetic.py", line 169, in evolve
    fitness = self.obective_function(parent)
  File "/usr/local/lib/python3.8/dist-packages/llama/rl/agents/ga/genetic.py", line 151, in obective_function
    obs, reward, done, _ = self.env.step(action_dic)   
  File "/usr/local/lib/python3.8/dist-packages/gym/core.py", line 314, in step
    observation, reward, done, info = self.env.step(action)
  File "/usr/local/lib/python3.8/dist-packages/sumogym/abstract/mod_manager.py", line 66, in step
    self.run_steps()
  File "/usr/local/lib/python3.8/dist-packages/sumogym/sumogym.py", line 260, in run_steps
    self.perform_action(None)
  File "/usr/local/lib/python3.8/dist-packages/sumogym/sumogym.py", line 255, in perform_action
    self.update_gym_tls()
  File "/usr/local/lib/python3.8/dist-packages/sumogym/sumogym.py", line 236, in update_gym_tls
    tl.update(self.sumo_time_step)
  File "/usr/local/lib/python3.8/dist-packages/sumogym/traffic_lights/tl_gym_static.py", line 123, in update
    self.update_db(sumo_time_step)
  File "/usr/local/lib/python3.8/dist-packages/sumogym/traffic_lights/tl_gym.py", line 440, in update_db
    stage_id = traci.trafficlight.getRedYellowGreenState(self.tl_id)
  File "/usr/local/lib/python3.8/dist-packages/traci/step.py", line 116, in tracingWrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/traci/step.py", line 116, in tracingWrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/traci/step.py", line 116, in tracingWrapper
    return method(*args, **kwargs)
  [Previous line repeated 977 more times]
  File "/usr/local/lib/python3.8/dist-packages/traci/_trafficlight.py", liRecursionError: maximum recursion depth exceeded in comparisonne 176, in getRedYellowGreenState
    return self._getUniversal(tc.TL_RED_YELLOW_GREEN_STATE, tlsID)
  File "/usr/local/lib/python3.8/dist-packages/traci/domain.py", line 147, in _getUniversal
    return _parse(self._retValFunc, varID, self._getCmd(varID, objectID, format, *values))
  File "/usr/local/lib/python3.8/dist-packages/traci/domain.py", line 152, in _getCmd
    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)
  File "/usr/local/lib/python3.8/dist-packages/traci/connection.py", line 189, in _sendCmd
    return self._sendExact()
  File "/usr/local/lib/python3.8/dist-packages/traci/connection.py", line 102, in _sendExact
    err = result.readString()
  File "/usr/local/lib/python3.8/dist-packages/traci/storage.py", line 68, in readString
    length = self.read("!i")[0]
  File "/usr/local/lib/python3.8/dist-packages/traci/storage.py", line 37, in read
    self._pos += struct.calcsize(format)

RecursionError: maximum recursion depth exceeded in comparison
```
**libsumo==1.14.1 traci==1.14.1 sumolib==1.14.1**

**SUMO-version: Eclipse SUMO sumo Version v1_14_1+1686-349c20d003f**

**operating system: amd64/ubuntu:20.04**

**Comment by jmlouw** [comment]
This issue may be helpful: https://stackoverflow.com/questions/25105541/python-quicksort-runtime-error-maximum-recursion-depth-exceeded-in-cmp/36592250#36592250

**Comment by namdre** [comment]
This might be an issue with our command logging. Can you remove the 'traceFile' parameter for the `traci.start` command and try again?
