### ISSUE TITLE
Get Neighbors Doesn't work in concurrent agents using libtraci

### ISSUE THREAD

**Issue by mahyarsadeghi** [eclipse/sumo#12976]
According to the issue #12475  libtraci is concurrent now. I have tested several apis and it works concurrently. One of the important functions that don't work for my parallel agents, is getNeighbors. Actions in agents are running parallelly and also there are other agents as well. When I ask for the neighbors of one particular agent, the other functionalities don't work and simulation crashes. Here is the error:
```
***  Uncaught Exception for agent CAV-fast_veh2  ***
Exception in thread "main" ***  Uncaught Exception for agent CAV-fast_veh  ***
java.lang.UnknownError: send failed: Socket reset by peer
	at org.eclipse.sumo.libtraci.libtraciJNI.Vehicle_setMaxSpeed(Native Method)
	at org.eclipse.sumo.libtraci.Vehicle.setMaxSpeed(Vehicle.java:816)
	at Agents.VehicleAgent$3.action(VehicleAgent.java:153)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
	at jade.core.Agent.run(Agent.java:1524)
	at java.base/java.lang.Thread.run(Thread.java:1589)
java.lang.UnknownError: tcpip::Socket::recvAndCheck @ recv: Socket reset by peer
	at org.eclipse.sumo.libtraci.libtraciJNI.Vehicle_getNeighbors(Native Method)
	at org.eclipse.sumo.libtraci.Vehicle.getNeighbors(Vehicle.java:280)
	at Agents.VehicleAgent$2.action(VehicleAgent.java:117)
	at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
	at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
	at jade.core.Agent.run(Agent.java:1524)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```
Am I missing something or there's a possibility to make it work concurrently. 
I'm using libtraci 1.17  snapshot and sumo 1.16

**Comment by behrisch** [comment]
I cannot reproduce it just by triggering many concurrent "getNeighbors" requests. Can you share more of your code? Maybe a different method is causing the problem. Do you use subscriptions?

**Comment by mahyarsadeghi** [comment]
Yes I can share the codes.
Anyway, I don't use subscription.
How should I subscribe it?

**Comment by behrisch** [comment]
I just meant [traci subscriptions](https://sumo.dlr.de/docs/TraCI/Object_Variable_Subscription.html). Please attach a minimal failing example here or link to a public github repo.

**Comment by mahyarsadeghi** [comment]
Ok got it. I will try with subscriptions. But for the code, I have shared it in issue  #12475 and you closed the issue I think last week. You were able to run the codes I shared there. If it is possible, get those codes again, in VehicleAgent.java, I think I have commented getNeighbors or you can call a simple one , inside a behavior. Anyway, I will give you the codes by tomorrow.

**Comment by mahyarsadeghi** [comment]
Here is the link to the zip file to the codes, similar to the previous one. In AgenteManager.java I'm creating the vehicle agents, you can do the subscription there, I'm using libtraci 1.17, with sumo 1.16 here and also  jade jar file. In vehicleAgent.java file you can see I'm requesting for getNeighbors there. If you don't have access to the file let me know.
https://drive.google.com/file/d/1uYewN4uxEMJZgoWiTa1dPKKXS-ATdEE3/view?usp=sharing

**Comment by mahyarsadeghi** [comment]
Hi. Did you check the codes? just let me know if there's an issue with running it.

**Comment by mahyarsadeghi** [comment]
I tried to subscribe the instructions, using the following code:
               ```
 IntVector instructions = new IntVector();
                instructions.add(Constants.VAR_NEIGHBORS);
                Vehicle.subscribe(getVehicleID(),instructions);
```
But I receive the following error:

Error: Storage::readChar(): invalid position

The sumo version is 1.16 and libtraci is sanpshot 1.17.  I think this problem can be solved with subscription, rather than thinking of concurrency. What am I missing?

**Comment by behrisch** [comment]
Sorry about leading you on this path. Subscriptions currently only work with parameterless functions. Since getNeighbors has a parameter, this won't work.
