### ISSUE TITLE
i can't understand what's going on ，because i can run sumocfg properly，when i try to use traci to train

### ISSUE THREAD

**Issue by wy12184163** [eclipse/sumo#13439]
E:\program\ananconda\python.exe G:\sumotest\1\parkingArea_demo\SAC.py 
Warning: Environment variable SUMO_HOME is not set properly, disabling XML validation. Set 'auto' or 'always' for web lookups.
Warning: Cannot read local schema 'D:\Program Files (x86)\sumo-1.16.0\tools/data/xsd/additional_file.xsd', XML validation will fail.
Error: invalid document structure
 In file 'parkingArea.add.xml'
 At line/column 2/1.

Quitting (on error).
Step #1.00 (0ms ?*RT. ?UPS, TraCI: 161ms, vehicles TOT 4 ACT 4 BUF 0)                     
Traceback (most recent call last):
  File "G:\sumotest\1\parkingArea_demo\SAC.py", line 118, in <module>
    traci.simulationStep()
  File "E:\program\ananconda\lib\site-packages\traci\main.py", line 199, in simulationStep
    return connection.check().simulationStep(step)
  File "E:\program\ananconda\lib\site-packages\traci\connection.py", line 363, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "E:\program\ananconda\lib\site-packages\traci\connection.py", line 225, in _sendCmd
    return self._sendExact()
  File "E:\program\ananconda\lib\site-packages\traci\connection.py", line 135, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

**Comment by namdre** [comment]
make sure that SUMO_HOME is defined within your environment: https://sumo.dlr.de/docs/Basics/Basic_Computer_Skills.html#sumo_home
