### ISSUE TITLE
errors when running simulation

### ISSUE THREAD

**Issue by zapcity** [eclipse/sumo#13600]
My code works correctly without error when run on Windows with sumo v 1.18.0. I however get errors when my code runs on Ubuntu linux, apparently at the same version i.e. 1.18.0

I initially installed sumo on ubuntu via `sudo apt-get install sumo sumo-tools sumo-doc`. A `pip list` relieved that sumolib was at version 1.18.0

I was getting the following errors when I ran my code:

```
traci.exceptions.TraCIException: Get Induction Loop Variable: unsupported variable 0x23 specified
Exception ignored in: <function CustomEnv.__del__ at 0x7ff55237dc10>
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Traceback (most recent call last):
Quitting (on error).
  File "vramp.py", line 248, in __del__
  File "vramp.py", line 244, in close
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/main.py", line 262, in close
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/connection.py", line 396, in close
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/connection.py", line 231, in _sendCmd
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/connection.py", line 130, in _sendExact
OSError: [Errno 9] Bad file descriptor
```

I managed to get rid of the `traci.exceptions.TraCIException: Get Induction Loop Variable: unsupported variable 0x23 specified` error by commenting out my usage of `traci.inductionloop.getIntervalOccupancy()`. Not sure why this is a problem, as it works fine in Windows.

Regarding the `Exception ignored in: <function CustomEnv.__del__ at 0x7ff55237dc10>` and `OSError: [Errno 9] Bad file descriptor`  error. I believe this has to do with `self.close()` and python thinks I'm closing a file descriptor named `self`,  in the following section of code:

```
    def close(self):
        if self.sumo is None:
            return
        
        traci.switch(self.label)
        traci.close()
        self.sumo = None

    def __del__(self):
        self.close()
```

I went back to update sumo to the most recent using:

```
sudo add-apt-repository ppa:sumo/stable
sudo apt-get update
sudo apt-get install sumo sumo-tools sumo-doc
```

This seems to have fixed my usage of `traci.inductionloop.getIntervalOccupancy(id)'. However, I'm still getting an error related to a file descriptor:

```
Exception ignored in: <function CustomEnv.__del__ at 0x7ffae9c73c10>
Traceback (most recent call last):
Step #60.00  File "sumo_code.py", line 248, in __del__TOT 80 ACT 63 BUF 170)
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
  File "vramp.py", line 244, in close
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/main.py", line 262, in close
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/connection.py", line 396, in close
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/connection.py", line 231, in _sendCmd
  File "/home/ubuntu/z/lib/python3.8/site-packages/traci/connection.py", line 130, in _sendExact
OSError: [Errno 9] Bad file descriptor
```

Thanks for any help.

**Comment by zapcity** [comment]
Thanks for your help. I managed to resolve the error related to the bad file descriptor, as it was caused by a different python library.

Just to reiterate, I have the following Linux setup:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"

sumolib   1.18.0
traci     1.18.0
```

I have the same python package versions on Windows i.e. sumolib/traci 1.18.0.

Regarding the remaining issues, I provided a complete minimal example below that runs on windows 10 without error. However when run on Ubuntu I get a number of errors:

1. Firstly I get  `Error: Attribute 'freq' is missing in definition of inductionLoop 'loop1'.`. However when I include freq as follows: `<inductionLoop id="loop1" lane="E1_0" pos="10" period="10" freq="1" file="out.xml"/>` the error goes away.
2. I get an error related to the induction loop:
```
> python flow.py

 Retrying in 1 seconds
Loading configuration ... done.
Step #1.00Error: Answered with error to command 0xa0: Get Induction Loop Variable: unsupported variable 0x23 specified
Traceback (most recent call last):
  File "flow.py", line 14, in <module>
    occ = traci.inductionloop.getIntervalOccupancy("loop1")
  File "/home/ubuntu/beta/lib/python3.8/site-packages/traci/_inductionloop.py", line 119, in getIntervalOccupancy
    return self._getUniversal(tc.VAR_INTERVAL_OCCUPANCY, loopID)
  File "/home/ubuntu/beta/lib/python3.8/site-packages/traci/domain.py", line 147, in _getUniversal
    return _parse(self._retValFunc, varID, self._getCmd(varID, objectID, format, *values))
  File "/home/ubuntu/beta/lib/python3.8/site-packages/traci/domain.py", line 152, in _getCmd
    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)
  File "/home/ubuntu/beta/lib/python3.8/site-packages/traci/connection.py", line 231, in _sendCmd
    return self._sendExact()
  File "/home/ubuntu/beta/lib/python3.8/site-packages/traci/connection.py", line 144, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Get Induction Loop Variable: unsupported variable 0x23 specified
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
```

I'm guessing there are differences between the Windows and Linux versions of the sumolib/traci 1.18.0 packages, given I get the above errors.

Thanks for any help.

------------------------------------------------------

flow.py
```
import traci

sumo_cmd = [
    "sumo", 
    "-c", "flow.sumocfg"
    ]

label = "flow"
traci.start(sumo_cmd, label=label)
conn = traci.getConnection(label)

for _ in range(100):
    conn.simulationStep()
    occ = traci.inductionloop.getIntervalOccupancy("loop1")
    print(f"occ: {occ}")

conn.close()
```

flow.sumocfg
```
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/sumoConfiguration.xsd">

    <input>
        <net-file value="flow.net.xml"/>
        <route-files value="flow.rou.xml"/>
        <additional-files value="flow.add.loop.xml"/>
    </input>

</configuration>
```

flow.net.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<net version="1.16" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="-100.00,0.00,300.00,0.00" origBoundary="10000000000.00,10000000000.00,-10000000000.00,-10000000000.00" projParameter="!"/>

    <edge id=":J2_0" function="internal">
        <lane id=":J2_0_0" index="0" speed="13.89" length="0.10" shape="100.00,-1.60 100.00,-1.60"/>
    </edge>

    <edge id="E0" from="J1" to="J2" priority="-1">
        <lane id="E0_0" index="0" speed="13.89" length="200.00" shape="-100.00,-1.60 100.00,-1.60"/>
    </edge>
    <edge id="E1" from="J2" to="J3" priority="-1">
        <lane id="E1_0" index="0" speed="13.89" length="200.00" shape="100.00,-1.60 300.00,-1.60"/>
    </edge>

    <junction id="J1" type="dead_end" x="-100.00" y="0.00" incLanes="" intLanes="" shape="-100.00,0.00 -100.00,-3.20"/>
    <junction id="J2" type="priority" x="100.00" y="0.00" incLanes="E0_0" intLanes=":J2_0_0" shape="100.00,0.00 100.00,-3.20 100.00,0.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="J3" type="dead_end" x="300.00" y="0.00" incLanes="E1_0" intLanes="" shape="300.00,-3.20 300.00,0.00"/>

    <connection from="E0" to="E1" fromLane="0" toLane="0" via=":J2_0_0" dir="s" state="M"/>

    <connection from=":J2_0" to="E1" fromLane="0" toLane="0" dir="s" state="M"/>

</net>
```

flow.rou.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-07-13 21:33:32 by Eclipse SUMO netedit Version 1.18.0
-->

<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">
    <!-- Vehicles, persons and containers (sorted by depart) -->
    <flow id="f_0" begin="0.00" from="E0" to="E1" end="3600.00" vehsPerHour="1800.00"/>
</routes>
```

flow.add.loop.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<additional>
    <inductionLoop id="loop1" lane="E1_0" pos="10" period="10" file="out.xml"/>
</additional>
```

**Comment by RNippold** [comment]
I will have a look...

**Comment by RNippold** [comment]
Runs without problems under fedora37. However, fedora uses a different Python version (3.11.4). Also, I only tried it with SUMO v1_18_0+0360-d2eaeb5375e, not the 1.18.0 release version. I will try to get an Ubuntu vm and try again with this setup.

**Comment by RNippold** [comment]
I cannot reproduce the error on an Ubuntu 22.04 vm (unfortunately not 20.04) with sumo-1.18.0, everything works as expected. Did you build SUMO yourself, or did you use a binary version provided elsewhere? Could you try to build SUMO yourself, as described here: https://sumo.dlr.de/docs/Installing/Linux_Build.html?

**Comment by m-kro** [comment]
Closing due to inactivity. @zapcity In case you still haven't resolved your problem, please post here again.

**Comment by bulbulemadeenah11** [comment]
this helped me thank you I reverted the use of induction loop and went for manual approach
