### ISSUE TITLE
error when running the city_mobil example

### ISSUE THREAD

**Issue by uwmyuan** [eclipse/sumo#4081]
Hi,

I run the example following the [instructions](http://sumo.dlr.de/wiki/Tutorials/CityMobil). However, I got the following errors. My env is win10 and py3.
```
..\city_mobil>python createNet.py
Success.

..\city_mobil>python simpleManager.py -g
Traceback (most recent call last):
  File "simpleManager.py", line 63, in <module>
    vehicleControl.init(SimpleManager())
  File "..\city_mobil\vehicleControl.py", line 104, in init
    doStep()
  File "..\city_mobil\vehicleControl.py", line 206, in doStep
    for veh, subs in traci.vehicle.getSubscriptionResults().iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```
I realize the py code may be in py2 instead of py3. So I change the `iteritems` to `items` according to the [manual](https://docs.python.org/3/library/stdtypes.html#dict.items). And I got the following errors.
```
..\city_mobil>python simpleManager.py -g
Traceback (most recent call last):
  File "..\city_mobil\vehicleControl.py", line 104, in init
    doStep()
  File "..\city_mobil\vehicleControl.py", line 240, in doStep
    setting.manager.cyberCarArrived(vehicleID, edge)
  File "simpleManager.py", line 46, in cyberCarArrived
    vehicleControl.leaveStop(person)
  File "..\city_mobil\vehicleControl.py", line 144, in leaveStop
    traci.vehicle.setStop(vehicleID, v.target, v.targetPos, 0, delay)
  File "C:\Program Files (x86)\DLR\Sumo\tools\traci\_vehicle.py", line 731, in setStop
    tc.TYPE_BYTE, laneIndex, tc.TYPE_INTEGER, duration, tc.TYPE_BYTE, flags)
struct.error: required argument is not an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simpleManager.py", line 63, in <module>
    vehicleControl.init(SimpleManager())
  File "..\city_mobil\vehicleControl.py", line 107, in init
    traci.close()
  File "C:\Program Files (x86)\DLR\Sumo\tools\traci\__init__.py", line 165, in close
    _connections[""].close(wait)
  File "C:\Program Files (x86)\DLR\Sumo\tools\traci\connection.py", line 307, in close
    self._sendExact()
  File "C:\Program Files (x86)\DLR\Sumo\tools\traci\connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: The second stop parameter must be the end position along the edge given as a double.
```
Could you share any clue to fix this error? Thanks.

**Comment by behrisch** [comment]
Using python2 is definitely an option but you could also try the fix just committed.
