### ISSUE TITLE
netedit crashes when trying to open or create a network

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4289]

**Comment by namdre** [comment]
@palvarezlopez Can you figure out why it did not crash for you?
The stacktrace was:

```
#0  0x000000000047e65a in GNEViewNet::getViewParent (this=0x0) at GNEViewNet.cpp:1198
#1  0x000000000044be00 in GNENet::requiereSaveAdditionals (this=0x7fffdc076530, value=true) at GNENet.cpp:1824
#2  0x000000000044e7a6 in GNENet::insertAdditional (this=0x7fffdc076530, additional=0x7fffdc07ef40) at GNENet.cpp:2093
#3  0x000000000043b5fb in GNENet::GNENet (this=0x7fffdc076530, netBuilder=0x7fffdc0187b0) at GNENet.cpp:136
```
