### ISSUE TITLE
unsubscribe not working as expected

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#4325]
Reported by Lara

> 
> I'm using
> traci.vehicle.subscribe(vehid, varIDs=(tc.VAR_ROAD_ID, tc.VAR_ROUTE_ID, tc.VAR_NEXT_STOPS))
> to subscribe to the vehicles that are supposed to use the parking lots.
> Then I'm using traci.vehicle.getSubscriptionResults() to get my results.
> If one of the vehicles has 0 stops to do, I want to usubscribe the vechile, becasue I'm not going
> to monitor it anymore, so I use traci.vehicle.unsubscribe(vehid)
> Problem, the next simulation step I receive again updates for that vehicle, and my script crashes
> due to double unsubscription.
> 
> [07/05/2018 04:57:58 PM] DEBUG: [18115250] Unsubscribing from vehicle pedestrian_2_5235_tr, no
> additional stops.
> [07/05/2018 04:57:58 PM] DEBUG: [18115500] Unsubscribing from vehicle pedestrian_2_5235_tr, no
> additional stops. [07/05/2018 04:57:58 PM] CRITICAL: Fatal error at timestamp 18115.50
> Traceback (most recent call last):
>   File "./traci.parkings.manager.py", line 212, in _main
>     monitor.step(int(step*1000))
>   File "./traci.parkings.manager.py", line 91, in step
>     self.update_vehicles_db(s)
>   File "./traci.parkings.manager.py", line 138, in update_vehicles_db
>     traci.vehicle.unsubscribe(vehicle)
>   File "/home/drone/Applications/SUMO/sumo-git/sumo/tools/traci/domain.py", line 151, in unsubscribe
>     self._subscribeID, 0, 2**31 - 1, objectID, [])
>   File "/home/drone/Applications/SUMO/sumo-git/sumo/tools/traci/connection.py", line 226, in
> _subscribe result = self._sendExact()
>   File "/home/drone/Applications/SUMO/sumo-git/sumo/tools/traci/connection.py", line 105, in
> _sendExact raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
> traci.exceptions.TraCIException: The subscription to remove was not found.
> 
> the 18115250 and 18115500 are the 2 consecutive time stamps.
> The sequence of calls are:
> 18115250: res = traci.vehicle.getSubscriptionResults()
>           for vehid, data in res.items():
>                 ... check the stops left ...
>                 traci.vehicle.unsubscribe(vehid)
> 18115500: res = traci.vehicle.getSubscriptionResults()
>           for vehid, data in res.items():
>                 ... check the stops left ...
>                 traci.vehicle.unsubscribe(vehid)
>         ### !!! CRASH !!! ###

**Comment by namdre** [comment]
we don't even have a singe python traci test for unsubscribe()

**Comment by namdre** [comment]
original bug report was retracted as invalid but we could still use some tests
