### ISSUE TITLE
Error with Traas and SUMO version dismatch

### ISSUE THREAD

**Issue by ZoeShaw101** [eclipse/sumo#4893]
```
Error: tcpip::Storage::readIsSafe: want to read 8 bytes from Storage, but only 4 remaining
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at de.tudresden.sumo.util.Query.doSimulationStep(Unknown Source)
	at de.tudresden.sumo.util.CommandProcessor.do_SimulationStep(Unknown Source)
	at it.polito.appeal.traci.SumoTraciConnection.do_timestep(Unknown Source)
	at it.polito.appeal.traci.SumoTraciConnection.do_timestep(Unknown Source)
	at group.simulation.traffic.service.SumoService.sumoDemo(SumoService.java:19)
```
 Error with Traas and SUMO  version dismatch,have solved this problems?

**Comment by namdre** [comment]
http://sumo.dlr.de/wiki/FAQ#Error:_tcpip::Storage::readIsSafe:_want_to_read_8_bytes_from_Storage.2C_but_only_4_remaining

Just update TraaS to match your SUMO version.
