### ISSUE TITLE
cannot import libsumo "ModuleNotFoundError: No module named 'libsumo.libsumo'"

### ISSUE THREAD

**Issue by Knight-H** [eclipse/sumo#4986]
I am trying to replicate the solved issue #4780 . I installed sumo 1.1.0 from source and  built it with cmake with the following output:

$ cmake ../..
-- Setting build type to 'Release' as none was specified.
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BINARY_DIR: /opt/sumo/build/cmake-build2
-- CMAKE_SOURCE_DIR: /opt/sumo
\-- 
-- Platform: 
--     Host: Linux-4.15.0-1026-gcp x86_64
--     Target: Linux-4.15.0-1026-gcp x86_64
--     CMake: 3.10.2
--     CMake generator: Unix Makefiles
--     CMake build tool: /usr/bin/make
--     Compiler: GNU 7.3.0
\-- 
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.7") 
-- Found Python: /usr/bin/python3.6
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Found XercesC: /usr/lib/x86_64-linux-gnu/libxerces-c.so (found version "3.2.0") 
-- Found Proj: /usr/lib/x86_64-linux-gnu/libproj.so
-- Found Fox: -L/usr/lib/x86_64-linux-gnu -lFOX-1.6 -lX11 -lXext -lfreetype -lfontconfig -lXft -lXcursor -lfreetype -lfontconfig -lfreetype -lGL -lGLU -ldl -lpthread -lrt -ljpeg -lpng -ltiff -lz -lGLU -lGL
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found GDAL: /usr/lib/libgdal.so  
-- Could NOT find osgGA (missing: OSGGA_LIBRARY OSGGA_INCLUDE_DIR) 
-- Could NOT find osgViewer (missing: OSGVIEWER_LIBRARY OSGVIEWER_INCLUDE_DIR) 
-- Could NOT find osgUtil (missing: OSGUTIL_LIBRARY OSGUTIL_INCLUDE_DIR) 
-- Could NOT find osgDB (missing: OSGDB_LIBRARY OSGDB_INCLUDE_DIR) 
-- Could NOT find osgText (missing: OSGTEXT_LIBRARY OSGTEXT_INCLUDE_DIR) 
-- Could NOT find osg (missing: OSG_LIBRARY OSG_INCLUDE_DIR) 
-- Could NOT find OpenThreads (missing: OPENTHREADS_LIBRARY OPENTHREADS_INCLUDE_DIR) 
-- Could NOT find OpenSceneGraph (missing: OPENSCENEGRAPH_LIBRARIES OPENSCENEGRAPH_INCLUDE_DIR) (Required is at least version "3.4.0")
-- Could NOT find GL2PS (missing: GL2PS_LIBRARY GL2PS_INCLUDE_DIR) 
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3.0")
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Enabled features: Linux-4.15.0-1026-gcp x86_64 GNU 7.3.0 Release Proj GUI GDAL
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/sumo/build/cmake-build2

I made sure that the output showed Python 3.6.7 as:
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.7") 
-- Found Python: /usr/bin/python3.6

However, when I tried the exact same code as the mentioned closed issue:
if 'SUMO_HOME' in os.environ:
tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
sys.path.append(tools)
else:
sys.exit("please declare environment variable 'SUMO_HOME'")

from sumolib import checkBinary # noqa
import traci
import sumolib
import libsumo as blah

This results in the following error:
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    import libsumo as blah
  File "/opt/sumo/tools/libsumo/\_\_init__.py", line 15, in <module>
    from .libsumo import *  # noqa
ModuleNotFoundError: No module named 'libsumo.libsumo'

In which if I go to the directory of $SUMO_HOME/tools/libsumo  , there is only file 1 \_\_init__.py
/opt/sumo/tools/libsumo$ ls
\_\_init__.py  \_\_pycache__
/opt/sumo/tools/libsumo$ cat *
\# Eclipse SUMO, Simulation of Urban MObility; see https://eclipse.org/sumo
\# Copyright (C) 2018-2018 German Aerospace Center (DLR) and others.
\# This program and the accompanying materials
\# are made available under the terms of the Eclipse Public License v2.0
\# which accompanies this distribution, and is available at
\# http://www.eclipse.org/legal/epl-v20.html
\# SPDX-License-Identifier: EPL-2.0

\# @file    \_\_init__.py
\# @author  Benjamin Striner
\# @author  Michael Behrisch
\# @date    2018-06-05
\# @version $Id$

from .libsumo import *  # noqa
cat: \_\_pycache__: Is a directory

I'm not sure what I am doing wrong here, am I missing something in the docs?
In the docs i found http://sumo.dlr.de/wiki/Libsumo which says that i would get libsumo.py and a _libsumo.so, but I search for the _libsumo.so and I found nothing.

**Comment by Knight-H** [comment]
whoops again, I forgot the line swig 

-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR) (Required is at least version "3.0")

and in the https://github.com/eclipse/sumo/blob/master/src/libsumo/CMakeLists.txt was written clearly that it needed swig in line 40: 
if(SWIG_FOUND)
