### ISSUE TITLE
Execution error of OSM Web Wizard

### ISSUE THREAD

**Issue by diallitoz** [eclipse/sumo#5000]
Hi, when I try to run "python osmWebWizard.py" on the command line from within the sumo/tools folder I got the following error : 
File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Recovering
Recovering

when I hit "Generate Scenario" button.

I use Ubuntu 18.04, Sumo 1.1.0 Python 2.7.15 (I also tried with Python 3)

Please, someone has any idea of this problem?
Thanks

**Comment by behrisch** [comment]
You probably did not set the SUMO_HOME environment variable and now it does not find sumo-gui. Please post the full log, if this is not the error.

**Comment by diallitoz** [comment]
> You probably did not set the SUMO_HOME environment variable and now it does not find sumo-gui. Please post the full log, if this is not the error.

Hello,
Thank for your answer.
I already set the SUMO_HOME environment as permanently in the .bashrc file. I can run the sumo-gui without any problem. I can not just run the osmWebWizard properly.

**Comment by behrisch** [comment]
Please post the full log / console output.

**Comment by diallitoz** [comment]
> Please post the full log / console output.

$ python osmWebWizard.py
Building scenario in '/home/diallo/Ma thèse/2019/Simulateurs/sumo-src-1.1.0/sumo-1.1.0/tools/2019-01-08-10-16-30'
Downloading map data
200 OK
Converting map data
Traceback (most recent call last):
  File "osmWebWizard.py", line 432, in build
    builder.build()
  File "osmWebWizard.py", line 227, in build
    osmBuild.build(options)
  File "/home/diallo/Ma thèse/2019/Simulateurs/sumo-src-1.1.0/sumo-1.1.0/tools/osmBuild.py", line 122, in build
    subprocess.call(netconvertOpts + ["--save-configuration", cfg], cwd=options.output_directory)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering

**Comment by behrisch** [comment]
Can you retry from a directory without spaces / accented characters?

**Comment by diallitoz** [comment]
> Please post the full log / console output.

$ python osmWebWizard.py
Building scenario in '/home/diallo/Ma thèse/2019/Simulateurs/sumo-src-1.1.0/sumo-1.1.0/tools/2019-01-08-10-16-30'
Downloading map data
200 OK
Converting map data
Traceback (most recent call last):
  File "osmWebWizard.py", line 432, in build
    builder.build()
  File "osmWebWizard.py", line 227, in build
    osmBuild.build(options)
  File "/home/diallo/Ma thèse/2019/Simulateurs/sumo-src-1.1.0/sumo-1.1.0/tools/osmBuild.py", line 122, in build
    subprocess.call(netconvertOpts + ["--save-configuration", cfg], cwd=options.output_directory)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering

> Can you retry from a directory without spaces / accented characters?

Yes. But i have the same error

$ python osmWebWizard.py
Building scenario in '/home/diallo/maThese/2019/Simulateurs/sumo-src-1.1.0/sumo-1.1.0/tools/2019-01-08-11-57-44'
Downloading map data
200 OK
Converting map data
Traceback (most recent call last):
  File "osmWebWizard.py", line 432, in build
    builder.build()
  File "osmWebWizard.py", line 227, in build
    osmBuild.build(options)
  File "/home/diallo/maThese/2019/Simulateurs/sumo-src-1.1.0/sumo-1.1.0/tools/osmBuild.py", line 122, in build
    subprocess.call(netconvertOpts + ["--save-configuration", cfg], cwd=options.output_directory)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering
Recovering

**Comment by behrisch** [comment]
I suppose there is no bin dir in the place where SUMO_HOME points too. Please add a symbolic link to the directory or just use the sumo version from the ppa http://sumo.dlr.de/wiki/Downloads#Repositories

**Comment by saifhitawala** [comment]
I am also getting a similar issue. Here is my log:
-------

Building scenario in '/home/shitawala/sumo-dev/resources/scenes/conn'
Downloading map data
200 OK
Converting map data
Traceback (most recent call last):
  File "/home/shitawala/sumo-dev/sumosim/tools/osmWebWizard.py", line 372, in build
    builder.build()
  File "/home/shitawala/sumo-dev/sumosim/tools/osmWebWizard.py", line 179, in build
    osmBuild.build(options)
  File "/usr/share/sumo/tools/osmBuild.py", line 122, in build
    subprocess.call(netconvertOpts + ["--save-configuration", cfg], cwd=options.output_directory)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'netconvertD': 'netconvertD'

Recovering
Recovering
Recovering

-------
I also tried the suggested sumo version following these steps but it did not work (no bin directory created in SUMO_HOME location after these steps):

sudo add-apt-repository ppa:sumo/stable
sudo apt-get update
sudo apt-get install sumo sumo-tools sumo-doc

Note that I am also able to run sumo-gui and that this issue did not occur before the sumo update released recently.

Thanks!

**Comment by diallitoz** [comment]
> I suppose there is no bin dir in the place where SUMO_HOME points too. Please add a symbolic link to the directory or just use the sumo version from the ppa http://sumo.dlr.de/wiki/Downloads#Repositories

Hi,
There is a bin dir in the Sumo folder. It just contains two makefiles. 
I already use this version of Sumo from the PPA.

**Comment by behrisch** [comment]
seems to be resolved

**Comment by ZenM-code** [comment]
Hi, 
When I click generate scenario, I get the following error in the terminal 
osmWebWizard.py: error: typemap file "home/zen/sumo/data/typemap/osmPolyconvert.typ.xml" not found

When following this path, this file is indeed there. 
I am using sumo v1.4
Can anyone tell me what to do next ?

**Comment by behrisch** [comment]
@ZenM-code Please do not reactivate closed tickets unless you have the same symptoms (open an new one instead). It looks like your definition of SUMO_HOME is missing the leading "/" and should be "/home/zen/sumo".

**Comment by ZenM-code** [comment]
> @ZenM-code Please do not reactivate closed tickets unless you have the same symptoms (open a new one instead). It looks like your definition of SUMO_HOME is missing the leading "/" and should be "/home/zen/sumo".

Apologies. That fixed it. Thanks :)

**Comment by tanzeelarubab** [comment]
> Hi, When I click generate scenario, I get the following error in the terminal osmWebWizard.py: error: typemap file "/home/sumo/data/typemap/osmPolyconvert.typ.xml" not found

please help me to recover error

**Comment by namdre** [comment]
see #9871

**Comment by anissya** [comment]
i have the same problem, ho to solve it ?


(base) C:\Users\Anis Natasya>cd C:\Program Files (x86)\Eclipse\Sumo\tools

(base) C:\Program Files (x86)\Eclipse\Sumo\tools>python osmWebWizard.py
Cannot create directory 'C:\Program Files (x86)\Eclipse\Sumo\tools\2022-03-17-21-09-59'
Building scenario in 'C:\Users\Anis Natasya\Sumo\2022-03-17-21-09-59'
Downloading map data
504 Gateway Timeout
Converting map data
Written configuration to 'osm.netccfg'
Parsing types from 'C:\Program Files (x86)\Eclipse\Sumo\data\typemap\osmNetconvert.typ.xml' ... done.
Error: Could not open osm-file 'osm_bbox.osm.xml'.
Repeating initial error messages:
Could not open osm-file 'osm_bbox.osm.xml'.
Error: No nodes loaded.
Quitting (on error).
Written configuration to 'osm.polycfg'
Error: Could not open net-file 'osm.net.xml'.
Quitting (on error).
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\net\__init__.py", line 831, in readNet
    parse(gzip.open(filename), netreader)
  File "C:\anaconda\lib\gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "C:\anaconda\lib\gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Anis Natasya\\Sumo\\2022-03-17-21-09-59\\osm.net.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 487, in build
    builder.build()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 296, in build
    self.edges = sumolib.net.readNet(os.path.join(self.tmp, self.files["net"])).getEdges()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\net\__init__.py", line 833, in readNet
    parse(filename, netreader)
  File "C:\anaconda\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "C:\anaconda\lib\xml\sax\expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "C:\anaconda\lib\xml\sax\saxutils.py", line 365, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "C:\anaconda\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\anaconda\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\anaconda\lib\urllib\request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\anaconda\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\anaconda\lib\urllib\request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>

Recovering
Recovering
Recovering

**Comment by namdre** [comment]
@anissya see #10350

**Comment by pattyperdersen** [comment]
My husband and i lost about 100, 000$ worth of bitcoins and USDT to a fake Cryptocurrency Investment platform. A few month back we saw and opportunity to invest and make a huge profit from the investment platform After a few time, we trial to withdraw our profit from our broker and we found out we're Scammed and this was really heartbroken so we Found a testimony on X About a Company Call Cyber Constable Intelligence, We send them a message as soon as possible and got a reply from their Expert and They got their tools ready and in less than 24 hours they recovery our lost Bitcoin with ease. 

Here is their Website at www cyber constable intelligence . com
