### ISSUE TITLE
Java Traas method Vehicle.setAdaptedTravletime() 4 parameters issue

### ISSUE THREAD

**Issue by grazmand** [eclipse/sumo#5251]
Using Java Traas method  Vehicle.setAdaptedTravletime(), the following errors appear on display in eclipse and Sumo console respectively:

eclipse: 
Exception in thread "main" it.polito.appeal.traci.TraCIException: SUMO error for command 196: Setting travel time using 4 parameters requires the begin time as first parameter.
	at de.tudresden.sumo.util.Query.queryAndVerify(Query.java:87)
	at de.tudresden.sumo.util.Query.queryAndVerifySingle(Query.java:217)
	at de.tudresden.sumo.util.CommandProcessor.do_job_set(CommandProcessor.java:66)
	at it.polito.appeal.traci.SumoTraciConnection.do_job_set(SumoTraciConnection.java:361)
	at maven.traas.Main.main(Main.java: yourNumberLine)

Sumo:
Error: Answered with error to command 0xc4: Setting travel time using 4 parameters requires the begin time as first parameter.
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

The errors appear despite using 5 parameters as needed instead of 4 as the error message claims.

**Comment by namdre** [comment]
fixed with 49fcffccc3149d06d091ee41d5875d50b7b44d85
