### ISSUE TITLE
sumolib can't read net

### ISSUE THREAD

**Issue by gumblex** [eclipse/sumo#5399]
In the current master checkout, the `sumolib.net.readNet` is broken:

```
>>> import sumolib.net  # noqa
>>> net1 = sumolib.net.readNet('test.net.xml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/dev/sumo/tools/sumolib/net/__init__.py", line 736, in readNet
    parse(filename, netreader)
  File "/usr/lib/python3.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 417, in StartElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 333, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/home/user/dev/sumo/tools/sumolib/net/__init__.py", line 672, in startElement
    elif self._currentProgram is not None:
AttributeError: 'NetReader' object has no attribute '_currentProgram'
```

Version 1.1.0 is not broken.

**Comment by namdre** [comment]
Thanks for reporting
