### ISSUE TITLE
vehicleSetStop (TraaS, Webservice)

### ISSUE THREAD

**Issue by YenKang** [eclipse/sumo#5473]
Dear @namdre ,
I try to implement the **vehicleSetStop()** function and the follow codes are part of [Main.java](https://github.com/YenKang/Smart-Logistics-Plan/blob/master/eclipse%20workspace/java_wsClient/java_wsclient/Main.java)

```
   ws.vehicleAdd("v"+i, "car", "r1", i, 0, 0.1, (byte) 1); //0.01 m
   int simTime = ws.simulationGetCurrentTime(); // [in ms]
   System.out.println("simulation time:"+ simTime/1000 + "s");
	
   int a= ws.vehicleGetLaneIndex("v0"); // LaneIndex is always 0
   System.out.println("v0 LaneIndex(int):"+a);
	
   byte v0_byte0 = intToByte(a);
   System.out.println("v0 byte0=" + v0_byte0);

   System.out.println("LANE POSITION:"+ ws.vehicleGetLanePosition("v0"));
   SumoStopFlags v0_stopFlag = new VehicleSetStop().getStopType();
   System.out.println("LANE v0_stopFlag:"+ v0_stopFlag);  //stopFlag is null
	
  if(simTime>30000) {
	ws.vehicleSetStop("v0", "gneE0", 316.7562361976065, v0_byte0, 10, v0_stopFlag); // this 
 would fail
     }
```
the **server** side shows the error:四月 14, 2019 7:50:48 下午**com.sun.xml.internal.ws.server.sei.TieHandler createResponse
嚴重: null**

the **client** side shows the error:
_**Exception in thread "main" com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: java.lang.NullPointerException Please see the server log to find more detail regarding exact cause of the failure.**_

How to correctly set up the parameter of **laneIndex** and **stopType** ?

sincerely,
Kang Yen

**Comment by namdre** [comment]
The webservice part of TraaS is not actively maintained at the moment (only the traci client library part).
The main reason for the webservice implementation was that TraCI did not support multiple clients in earlier SUMO versions. This is no longer the case so you should be fine with using the library directly for most use cases. 

I didn't even manage to start the ws_client example due to
```
Exception in thread "main" java.lang.IllegalArgumentException: de.tudresden.ws.ServiceImpl is not an interface
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:590)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
        at com.sun.xml.internal.ws.client.WSServiceDelegate$3.run(WSServiceDelegate.java:727)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.createProxy(WSServiceDelegate.java:723)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.createEndpointIFBaseProxy(WSServiceDelegate.java:805)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:436)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:404)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:386)
        at javax.xml.ws.Service.getPort(Service.java:119)
        at de.tudresden.ws.TraasWS.getServiceImplPort(TraasWS.java:72)
        at Main.main(Main.java:33)

```
