### ISSUE TITLE
sumo-gui crash when guiShape="truck/(semi)trailer"

### ISSUE THREAD

**Issue by gumblex** [eclipse/sumo#5510]
When vType guiShape="truck/semitrailer" or guiShape="truck/trailer", vehicle show as "simple shape", sumo-gui (git master) crashes on starting simulation.

```
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x0000558098a7b0bc in GUIVehicle::drawAction_drawCarriageClass(GUIVisualizationSettings const&, bool) const ()
[Current thread is 1 (Thread 0x7fd73c6a18c0 (LWP 24926))]
(gdb) bt
#0  0x0000558098a7b0bc in GUIVehicle::drawAction_drawCarriageClass(GUIVisualizationSettings const&, bool) const ()
#1  0x0000558098a71d32 in GUIBaseVehicle::drawAction_drawVehicleAsPolyWithCarriagges(GUIVisualizationSettings const&, bool) const ()
#2  0x0000558098a7c63d in GUIBaseVehicle::drawOnPos(GUIVisualizationSettings const&, Position const&, double) const ()
#3  0x000055809870b8b4 in GUIBaseVehicle::drawGL(GUIVisualizationSettings const&) const [clone .constprop.796] ()
#4  0x0000558098aa145c in GUIEdge::drawGL(GUIVisualizationSettings const&) const ()
#5  0x0000558098a8b761 in RTree<GUIGlObject*, GUIGlObject, float, 2, GUIVisualizationSettings, float, 8, 4>::Search(RTree<GUIGlObject*, GUIGlObject, float, 2, GUIVisualizationSettings, float, 8, 4>::Node*, RTree<GUIGlObject*, GUIGlObject, float, 2, GUIVisualizationSettings, float, 8, 4>::Rect*, int&, GUIVisualizationSettings const&) const ()
#6  0x0000558098a8b6d6 in RTree<GUIGlObject*, GUIGlObject, float, 2, GUIVisualizationSettings, float, 8, 4>::Search(RTree<GUIGlObject*, GUIGlObject, float, 2, GUIVisualizationSettings, float, 8, 4>::Node*, RTree<GUIGlObject*, GUIGlObject, float, 2, GUIVisualizationSettings, float, 8, 4>::Rect*, int&, GUIVisualizationSettings const&) const ()
#7  0x0000558098a8cf16 in SUMORTree::Search(float const*, float const*, GUIVisualizationSettings const&) const ()
#8  0x0000558098a8bae2 in LayeredRTree::Search(float const*, float const*, GUIVisualizationSettings const&) const ()
#9  0x0000558098aa7720 in GUIViewTraffic::doPaintGL(int, Boundary const&) ()
#10 0x0000558098a51bfb in GUISUMOAbstractView::paintGL() ()
#11 0x0000558098a51cf8 in GUISUMOAbstractView::onPaint(FX::FXObject*, unsigned int, void*) ()
#12 0x00007fd74f361f33 in FX::FXApp::dispatchEvent(_XEvent&) ()
    at /usr/lib/x86_64-linux-gnu/libFOX-1.6.so.0
#13 0x00007fd74f360cf3 in FX::FXApp::runOneEvent(bool) ()
    at /usr/lib/x86_64-linux-gnu/libFOX-1.6.so.0
#14 0x00007fd74f360d8d in FX::FXApp::run() ()
    at /usr/lib/x86_64-linux-gnu/libFOX-1.6.so.0
#15 0x00005580986f3263 in main ()
```

**Comment by namdre** [comment]
It crashes when trying to render truck/trailer with a vehicle length < 13m or truck/semitrailer with length < 9.5m

**Comment by angelobanse** [comment]
@namdre this keeps happening

**Comment by namdre** [comment]
now tracked in #9682
