### ISSUE TITLE
Crash due to conconcurrent access to _stepListeners

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#5610]
regression caused by [be136aca78e495ff]

**Comment by namdre** [comment]
Running https://github.com/lcodeca/PyPML/blob/v0.2/examples/simple.example.py
error is related to running traci in a profiler and handling an exception:

```
Exception: The total occupancy for parking area parkingArea_A0A1_1_17 is 50 but it must be equal to the one retrieved from SUMO: 49.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple.example.py", line 129, in <module>
    traci.close()
  File "/scr1/sumo/tools/traci/__init__.py", line 217, in close
    for listenerID in listenerIDs:
RuntimeError: dictionary changed size during iteration
```
