### ISSUE TITLE
Assertion `vNext >= vMin' failed ?

### ISSUE THREAD

**Issue by ChocolateDave** [eclipse/sumo#5838]
Hi everyone, i'm working on a speed limit project recently. While using traci.edge.setmaxspeed(), i got a assertion:

sumo: /build/sumo-tHynv2/sumo-1.2.0+dfsg1/src/microsim/cfmodels/MSCFModel.cpp:203: virtual double MSCFModel::finalizeSpeed(MSVehicle*, double) const: Assertion `vNext >= vMin' failed.
Traceback (most recent call last):
  File "core.py", line 164, in <module>
    Train(args.cuda, args.name, args.path, args.frameskip)
  File "core.py", line 124, in Train
    buffer.populate(1)
  File "/root/VSL/HDQN/lib/experience.py", line 368, in populate
    entry = next(self.experience_source_iter)
  File "/root/VSL/HDQN/lib/experience.py", line 176, in __iter__
    for exp in super(ExperienceSourceFirstLast, self).__iter__():
  File "/root/VSL/HDQN/lib/experience.py", line 97, in __iter__
    next_state, r, is_done, _ = env.step(action_n[0])
  File "/root/VSL/HDQN/env.py", line 197, in step
    traci.simulationStep()
  File "/usr/share/sumo/tools/traci/__init__.py", line 126, in simulationStep
    responses = _connections[""].simulationStep(step)
  File "/usr/share/sumo/tools/traci/connection.py", line 329, in simulationStep
    result = self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 105, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO

would you guys help me solve this?

**Comment by behrisch** [comment]
Can you share your scenario? Which car following model did you use?
