### ISSUE TITLE
random trips.py does not accept relative paths

### ISSUE THREAD

**Issue by alexdawn** [eclipse/sumo#6001]
Trying to run random_trips.py using git-bash and I get the following error: `ValueError: unknown url type: './model_input/oxford/abingdon_network.net.xml'` it appears that whatever library is being used to interpret the shell arguments doesn't recognise a relative path.

Full stack trace:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\/tools/randomTrips.py", line 521, in <module>
    if not main(get_options()):
  File "C:\Program Files (x86)\Eclipse\Sumo\/tools/randomTrips.py", line 395, in main
    net = sumolib.net.readNet(options.netfile)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\sumolib\net\__init__.py", line 741, in readNet
    parse(filename, netreader)
  File "C:\Tools\anaconda\envs\model_converter\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "C:\Tools\anaconda\envs\model_converter\lib\xml\sax\expatreader.py", line 105, in parse
    source = saxutils.prepare_input_source(source)
  File "C:\Tools\anaconda\envs\model_converter\lib\xml\sax\saxutils.py", line 364, in prepare_input_source
    f = urllib.request.urlopen(source.getSystemId())
  File "C:\Tools\anaconda\envs\model_converter\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Tools\anaconda\envs\model_converter\lib\urllib\request.py", line 510, in open
    req = Request(fullurl, data)
  File "C:\Tools\anaconda\envs\model_converter\lib\urllib\request.py", line 328, in __init__
    self.full_url = url
  File "C:\Tools\anaconda\envs\model_converter\lib\urllib\request.py", line 354, in full_url
    self._parse()
  File "C:\Tools\anaconda\envs\model_converter\lib\urllib\request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: './model_input/oxford/abingdon_network.net.xml'
```

**Comment by behrisch** [comment]
I agree that it is not the best of all error messages but if the file exists it works here. Are you sure the file is there?

**Comment by behrisch** [comment]
I am a bit hesitant to write a wrapper with another error message here, because if the parser supports reading from URLs and whatever this is a good thing and the error message is (in a sense) correct then or it is more of a python urllib issue. Please reopen if you disagree.
