### ISSUE TITLE
repeated call to libsumo.start gives wrong error message

### ISSUE THREAD

**Issue by passengerxuhongli** [eclipse/sumo#6240]
when i run this code,:

```

import os
import libsumo as traci

class SumoEnv(object):

    def __init__(self, sumo_cfg_file,
                 auto_start=True, auto_quit=True, no_warning=True, no_step_log=True):

        self._start_sumo_server(sumo_cfg_file,auto_start, auto_quit, no_warning, no_step_log)

        print('SumoEnv build')

    def __del__(self):

        self._close()
        print('SumoEnv close')

    def step(self):
        traci.simulationStep()

    def _close(self):
        traci.close()

    @staticmethod
    def _start_sumo_server(sumo_cfg_file, auto_start=True, auto_quit=True, no_warning=True,
                           no_step_log=True):
        sumo_home = os.environ['SUMO_HOME']
        sumo_bin = sumo_home + r'/bin/sumo'
        sumo_cmd = [sumo_bin, '-c', sumo_cfg_file, '-S', str(auto_start), '-Q', str(auto_quit), '--step-length', '1',
                    '-W', str(no_warning), '--no-step-log', str(no_step_log)]
        traci.start(sumo_cmd)


if __name__ == '__main__':
    sumo_cfg_file = r"C:\Users\aaa\Desktop\sences\test.sumocfg"
    for i in range(1000):
        env=SumoEnv(sumo_cfg_file)
        sim_time = 0
        while sim_time <= 400:
            env.step()
            sim_time += 1

```
error occurs: 
```
Loading configuration... done.
SumoEnv build
Loading configuration... done.
SumoEnv build
SumoEnv close
Traceback (most recent call last):
  File "C:/Users/aaaaa/Desktop/sumoenv_test/sumoenv.py", line 49, in <module>
    env.step()
  File "C:/Users/aaaa/Desktop/sumoenv_test/sumoenv.py", line 28, in step
    traci.simulationStep()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\libsumo\libsumo.py", line 121, in simulationStep
    simulation.step(step)
RuntimeError: SUMO error: A network was not yet constructed.
SumoEnv close
```

so i want to know where and how  A network was constructed in sumo

**Comment by behrisch** [comment]
The error message is probably misleading. Judging from your output, the second `start` is called before the first `close` which is currently not allowed. You could probably easily work around this by either setting env to None before assigning a new value or even better deleting the old env explicitly with `del env`. I am leaving this ticket open since we need to fix at least the error message.

**Comment by passengerxuhongli** [comment]
thank you and you are right: "the second start is called before the first close which is currently not allowed" and i works before assigning a new value or even better deleting the old env explicitly with del env。

while, i still want to know how and when "sumo network" constructed, where can i found them in source code?

**Comment by behrisch** [comment]
The code is mainly in https://github.com/eclipse/sumo/blob/master/src/libsumo/Simulation.cpp especially in the load method. But after having a look at the code I have to correct myself. What you tried should be possible.
