### ISSUE TITLE
make docs fails everywhere but on the build server

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#6384]
Probably some bleeding edge mkdocs is only installed there

**Comment by angelobanse** [comment]
it is surely the mkdocs-git-revision-date plugin, which we need version 0.2 or newer

**Comment by behrisch** [comment]
No it is not. This version is correct. The error message is:
```

WARNING -  Config value: 'site_favicon'. Warning: Unrecognised configuration name: site_favicon 
[macros] Macros arguments: {'module_name': 'main', 'include_yaml': []}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/macros/plugin.py", line 214, in _load_module
    module = importlib.import_module(python_module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/usr/lib/python3.6/site-packages/mkdocs/commands/build.py", line 240, in build
    config = config['plugins'].run_event('config', config)
  File "/usr/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/usr/lib/python3.6/site-packages/macros/plugin.py", line 261, in on_config
    self._load_module()
  File "/usr/lib/python3.6/site-packages/macros/plugin.py", line 234, in _load_module
    (python_module, self.project_dir))
ImportError: Macro plugin could not find custom 'main' module in '/home/micha/programming/sumo/docs/web'.

```

**Comment by angelobanse** [comment]
i found it. it is the "mkdocs-macros-plugin". In the most recent version of that plugin (0.3.2) this error occurs. We need to use version 0.2.4, which works fine.

**Comment by angelobanse** [comment]
`pip3 install mkdocs-macros-plugin==0.2.4`

**Comment by angelobanse** [comment]
Upgrading that plugin to the most recent version i was able to reproduce the error message you showed. I just downgraded it to 0.2.4 and now everything works fine.
