### ISSUE TITLE
 I tried to use Cadyts but was unable make it run. The  cadytsSumoController.jar file seems to be missing. I'm using sumo 1.3.1

### ISSUE THREAD

**Issue by komal230299** [eclipse/sumo#6429]

**Comment by behrisch** [comment]
There should be a file called cadyts-master-SNAPSHOT.jar in your release (at least on windows)

**Comment by komal230299** [comment]
hello behrisch
  I founda file called cadyts-master-SNAPSHOT.jar in the bin dir. but how to use that file in place of cadytsSumoController? as you said it should be picked up automatically by the cadytsIterate.py.
but still, I'm getting the following error
Command used= cadytsIterate.py -n network0.xml -r RoutesRou.xml -d realflow18.xml
Traceback (most recent call last):
  File "E:\sumo projects\detector-sumo_files\updated_w\cadytsIterate.py", line 167, in <module>
    main()
  File "E:\sumo projects\detector-sumo_files\updated_w\cadytsIterate.py", line 121, in main
    "-cntlastlink", options.cntlastlink], log)
  File "E:\sumo projects\detector-sumo_files\updated_w\duaIterate.py", line 176, in call
    retCode = subprocess.call(command, stdout=log, stderr=log)
  File "C:\Users\Komal\Anaconda3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Komal\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Komal\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by komal230299** [comment]
hello Michael 
The file you told is present in the given directory but still I'm getting following error
Command used= cadytsIterate.py -n network0.xml -r RoutesRou.xml -d realflow18.xml
Traceback (most recent call last):
  File "E:\sumo projects\detector-sumo_files\updated_w\cadytsIterate.py", line 167, in <module>
    main()
  File "E:\sumo projects\detector-sumo_files\updated_w\cadytsIterate.py", line 121, in main
    "-cntlastlink", options.cntlastlink], log)
  File "E:\sumo projects\detector-sumo_files\updated_w\duaIterate.py", line 176, in call
    retCode = subprocess.call(command, stdout=log, stderr=log)
  File "C:\Users\Komal\Anaconda3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Komal\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Komal\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by behrisch** [comment]
Do you have java installed and is it in your path? And if so which version?

**Comment by komal230299** [comment]
Hello behrisch,
 Thanks for helping me getting the error. I have downloaded Java and now it is working but it is taking too much time for calibration. So can you please tell what parameters need to be changed for reducing the calibration time

**Comment by komal230299** [comment]
the calibration is not moving forward from step 0

**Comment by komal230299** [comment]
Can you provide me with your input files so that I can try running those files and also for checking my input files

**Comment by behrisch** [comment]
You could try this one: https://sumo.dlr.de/extractTest.php?path=tools/assign/calibration/demand_adjustment

**Comment by behrisch** [comment]
No further feedback and cadyts is no longer part of the repo and the release
