### ISSUE TITLE
Cannot compile sumo 1.4.0

### ISSUE THREAD

**Issue by Trashcleaner** [eclipse/sumo#6460]
Hi, 
I have difficulties building the latest version of sumo (1.4.0) as well as today's version from master branch. I have another version of Sumo (1.2.0) currently installed.

I follow the regular procedure for buidling from sources from cmake-build directory.
`cmake ../..`
has following output:

```
-- CMAKE_BINARY_DIR: /home/obrusvit/Tools/sumo-1.4.0/build/cmake-build
-- CMAKE_SOURCE_DIR: /home/obrusvit/Tools/sumo-1.4.0
-- 
-- Platform: 
--     Host: Linux-4.15.0-72-generic x86_64
--     Target: Linux-4.15.0-72-generic x86_64
--     CMake: 3.10.2
--     CMake generator: Unix Makefiles
--     CMake build tool: /usr/bin/make
--     Compiler: GNU 7.4.0
-- 
-- Found Python: /usr/bin/python
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Found Proj: /usr/lib/x86_64-linux-gnu/libproj.so
-- Found Fox: -L/usr/lib/x86_64-linux-gnu -lFOX-1.6 -lX11 -lXext -lfreetype -lfontconfig -lXft -lXcursor -lfreetype -lfontconfig -lfreetype -lGL -lGLU -ldl -lpthread -lrt -ljpeg -lpng -ltiff -lz -lGLU -lGL
-- Could NOT find suitable FFmpeg.
-- Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAVADOC_EXECUTABLE Development) (found version "11.0.5")
-- Could NOT find Java (missing: Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVADOC_EXECUTABLE) (found version "11.0.5")
-- Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
CMake Warning at src/libsumo/CMakeLists.txt:83 (message):
  ENABLE_JAVA_BINDINGS is set but Java or JNI was not found.


-- CPACK_GENERATOR: ZIP
-- Enabled features: Linux-4.15.0-72-generic x86_64 GNU 7.4.0 Release Proj GUI GDAL OSG GL2PS SWIG
-- Configuring done
-- Generating done
-- Build files have been written to: /home/obrusvit/Tools/sumo-1.4.0/build/cmake-build
```

make has the following output:
```
[  0%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/GenericSAXHandler.cpp.o
[  0%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SUMOSAXAttributes.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SUMOSAXAttributesImpl_Binary.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SUMOSAXAttributesImpl_Xerces.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SUMOSAXAttributesImpl_Cached.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SUMOSAXHandler.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SUMOSAXReader.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SUMOXMLDefinitions.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/SAXWeightsHandler.cpp.o
[  1%] Building CXX object src/utils/xml/CMakeFiles/utils_xml.dir/XMLSubSys.cpp.o
[  2%] Linking CXX static library libutils_xml.a
[  2%] Built target utils_xml
[  2%] Generating version.h
Traceback (most recent call last):
  File "/home/obrusvit/Tools/sumo-1.4.0/src/../tools/build/version.py", line 70, in <module>
    main()
  File "/home/obrusvit/Tools/sumo-1.4.0/src/../tools/build/version.py", line 55, in main
    vcsFile = join(sumolib.version.GITDIR, GITFILE)
AttributeError: 'module' object has no attribute 'version'
src/CMakeFiles/generate-version-h.dir/build.make:60: recipe for target 'src/version.h' failed
make[2]: *** [src/version.h] Error 1
CMakeFiles/Makefile2:370: recipe for target 'src/CMakeFiles/generate-version-h.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-version-h.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by namdre** [comment]
The build fails because the version.py tool loads an older version of sumolib.
update environment variable SUMO_HOME to point to the new sumo version (i.e. /home/obrusvit/Tools/sumo-1.4.0/)

**Comment by Trashcleaner** [comment]
Variable SUMO_HOME was correctly set to the directory of new sumo version. This does not seem to be a problem. Is it possible that currently installed version on my system somehow interferes with newer version?
Any other suggestions? 
Thank you

**Comment by namdre** [comment]
Probably, the older version of sumolib comes earlier in the python load path and thus gets picked up first. You can either unistall the older version or use a virtual environment to hide it:
https://docs.python.org/3/tutorial/venv.html

**Comment by Trashcleaner** [comment]
An update: 
I just tried to compile versions 1.1.0, 1.2.0 and 1.3.1 and it was without problems. 
I tried to make clean, delete all build files, cmake again, repoint SUMO_HOME and compilation was done alright and sumo is working.
Building version 1.4.0 keeps crashing with exactly the same error output (after "Generating version.h").
Thanks

**Comment by namdre** [comment]
This is to be expected since the build process of  version 1.4 requires a new version of the  python library sumolib (that is part of sumo but gets picked up from the python environment). All older buils work with the older version of sumolib. The solution is outlined above.
