### ISSUE TITLE
"Error in num lanes with key" and "traci.exceptions.TraCIException: Vehicle 'ambulance_00.2' is not known"

### ISSUE THREAD

**Issue by ElizabethDuo** [eclipse/sumo#6479]
Hi guys,

I am trying to apply a list of lane change actions on a list of vehicles.
But it went wrong. The terminal output read

> Error in num lanes with key 
Traceback (most recent call last):
  File "my_highway_rl_test.py", line 141, in <module>
    _ = exp.run(10, 100, convert_to_csv=False)
  File "/home/elizabeth/0MA/flow/my_examples/multiagent_acclane/experiment_rl.py", line 140, in run
    state, reward, done, _ = self.env.step(state)
  File "/home/elizabeth/0MA/flow/my_examples/multiagent_acclane/my_highway_env.py", line 271, in step
    self.k.vehicle.apply_lane_change(rl_ids, rl_lane_actions)
  File "/home/elizabeth/0MA/flow/flow/core/kernel/vehicle/traci.py", line 963, in apply_lane_change
    veh_id, int(target_lane), 100000)
  File "/home/elizabeth/anaconda3/envs/MultiAgent/lib/python3.6/site-packages/traci/_vehicle.py", line 926, in changeLane
    "!BiBBBd", tc.TYPE_COMPOUND, 2, tc.TYPE_BYTE, laneIndex, tc.TYPE_DOUBLE, duration)
struct.error: ubyte format requires 0 <= number <= 255
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/elizabeth/0MA/flow/flow/envs/base.py", line 684, in terminate
    self.k.close()
  File "/home/elizabeth/0MA/flow/flow/core/kernel/kernel.py", line 109, in close
    self.simulation.close()
  File "/home/elizabeth/0MA/flow/flow/core/kernel/simulation/traci.py", line 64, in close
    self.kernel_api.close()
  File "/home/elizabeth/anaconda3/envs/MultiAgent/lib/python3.6/site-packages/traci/connection.py", line 363, in close
    self._sendExact()
  File "/home/elizabeth/anaconda3/envs/MultiAgent/lib/python3.6/site-packages/traci/connection.py", line 113, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Vehicle 'ambulance_00.2' is not known

And the sumo gui log read

> Error: Answered with error to command 0xc4: Vehicle 'ambulance_00.2' is not known
Error: Answered with error to command 0xc4: Wrong position in requestMessage after dispatching command. Expected command length was 37 but 23 Bytes were read.
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

'ambulance_00.2' is the name of the vehicle. 
I wonder what is happening and want to know how to fix that.
Any good ideas?
Please tell me! Thanks!

**Comment by namdre** [comment]
My guess is that you are using the Flow framework with an incompatible sumo version. However, you should take your question to the Flow maintainers because we cannot give support on Flow here.
