### ISSUE TITLE
tileGet.py does not work correctly when using bounding box as input

### ISSUE THREAD

**Issue by angelobanse** [eclipse/sumo#6499]
if a network is used as input everything works perfectly, but when a bounding box is specified as input, the images are downloaded, but the generated `settings.xml` file is incomplete and the script throws the following error:

```
Traceback (most recent call last):
  File ".\tileGet.py", line 172, in <module>
    get()
  File ".\tileGet.py", line 147, in get
    decals, options.prefix, net, options.layer)
  File ".\tileGet.py", line 85, in retrieveMapServerTiles
    upperLeft = net.convertLonLat2XY(lon, lat)
AttributeError: 'NoneType' object has no attribute 'convertLonLat2XY'
```

**python .\tileGet.py -b 13.39774,52.51801,13.40182,52.51988**

**Comment by holala-at** [comment]
The net object is not defined, a quick fix, provide a net file (-n) and adapt the script in line 151 to:
if options.net:
        net = sumolib.net.readNet(options.net)
        if not options.bbox:
            bbox = net.getBBoxXY()
            west, south = net.convertXY2LonLat(*bbox[0])
            east, north = net.convertXY2LonLat(*bbox[1])
