### ISSUE TITLE
LIBSUMO_AS_TRACI environment variable no longer works

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#7207]
probably as an effect of the tracing implementation
```
Traceback (most recent call last):
  File "create_poly_db.py", line 13, in <module>
    import traci
  File "/usr/local/share/sumo/tools/traci/__init__.py", line 30, in <module>
    from libsumo import *  # noqa
  File "/usr/local/share/sumo/tools/libsumo/__init__.py", line 20, in
<module>
    from .libsumo import simulation
  File "/usr/local/share/sumo/tools/libsumo/libsumo.py", line 65, in
<module>
    from traci import constants, exceptions, _vehicle, _person,
_trafficlight, _simulation
  File "/usr/local/share/sumo/tools/traci/_vehicle.py", line 32, in <module>
    from .main import legacyGetLeader
  File "/usr/local/share/sumo/tools/traci/main.py", line 66, in <module>
    vehicle = _vehicle.VehicleDomain()
AttributeError: partially initialized module 'traci._vehicle' has no
attribute 'VehicleDomain' (most likely due to a circular import)
```

**Comment by LucasAlegre** [comment]
Hi, I'm having this problem and I'm using sumo-tools version 1.10.0+dfsg1-1ubuntu1
What should I do?

**Comment by behrisch** [comment]
Please double check that you do not have an old version of the sumo tools somewhere in your installation or PYTHONPATH because it works here in our tests
