### ISSUE TITLE
Problem for traci.route.add() and traci.vehicle.addLegacy()

### ISSUE THREAD

**Issue by Shiyunyang-seu** [eclipse/sumo#7677]
Hi, I am so sorry to reopen the question. When I want to add a new route and also add a vehicle which is not in the rou.xml before the simulation.
And the command is ：
traci.route.add('new1',['--31452#1','--31452#0'])

Traceback (most recent call last):
  File "c:\Users\12611\Desktop\get_est_time.py", line 401, in <module>
    run()
  File "c:\Users\12611\Desktop\get_est_time.py", line 318, in run
    traci.route.add('new1',['--31452#1','--31452#0'])
  File "D:\sumo\tools\traci\_route.py", line 43, in add
    self._setCmd(tc.ADD, routeID, "l", edges)
  File "D:\sumo\tools\traci\domain.py", line 184, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "D:\sumo\tools\traci\connection.py", line 178, in _sendCmd
    return self._sendExact()
  File "D:\sumo\tools\traci\connection.py", line 95, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Could not add route.

Also, I want to add a route directly and add a new vehicle, the command is like:
routeID = '--31452#1 --31452#0'
traci.vehicle.addLegacy('test2', routeID, '1')
But also a error occurs:

Traceback (most recent call last):
  File "c:\Users\12611\Desktop\get_est_time.py", line 401, in <module>
    run()
  File "c:\Users\12611\Desktop\get_est_time.py", line 317, in run
    traci.vehicle.addLegacy(vehicle_id2, routeID, '1')
  File "D:\sumo\tools\traci\_vehicle.py", line 1432, in addLegacy
    self.addFull(vehID, routeID, typeID, depart, lane, str(pos), str(speed))
  File "D:\sumo\tools\traci\_vehicle.py", line 1445, in add
    arrivalLane, arrivalPos, arrivalSpeed, fromTaz, toTaz, line, personCapacity, personNumber)
  File "D:\sumo\tools\traci\domain.py", line 184, in _setCmd
    self._connection._sendCmd(self._cmdSetID, varID, objectID, format, *values)
  File "D:\sumo\tools\traci\connection.py", line 178, in _sendCmd
    return self._sendExact()
  File "D:\sumo\tools\traci\connection.py", line 95, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Invalid route '--31452#1 --31452#0' for vehicle 'test2'.
Thanks in advance!

**Comment by behrisch** [comment]
For the first question: Please make sure that there is no route with the same ID either from a route XML file or from a previous add. For the second: The route id should not contain the edge list but the id of a previously added route such as "new1".

**Comment by dawn-fm** [comment]
Hi, I have same issue as @Shiyunyang-seu.

I wonder if there are any workarounds to add vehicle with existing route, cuz I want to re-add used vehicles with same route after it finishes their trip.

Thank you.

**Comment by namdre** [comment]
if you added a route with `traci.route.add` you can re-use that routeID as often as you like.
