### ISSUE TITLE
ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by M-Colley** [eclipse/sumo#7902]
Hey, I just downloaded Version 1.8. 

I wanted to use the OSM Web Wizard, but when hitting Generate, the following error comes along. I did not find any information on any requirements besides SUMO and Python, am I missing something?

`Cannot create directory 'C:\Program Files (x86)\Eclipse\Sumo\tools\2020-12-02-19-24-49'
Building scenario in 'C:\Users\Mark\Sumo\2020-12-02-19-24-49'
Downloading map data
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 480, in build
    builder.build()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 189, in build
    osmGet.get(
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 124, in get
    readCompressed(conn, url.path, '<bbox-query n="%s" s="%s" w="%s" e="%s"/>' %
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 39, in readCompressed
    conn.request("POST", "/" + urlpath, """
  File "C:\Program Files\Inkscape\lib\python3.8\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Inkscape\lib\python3.8\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Inkscape\lib\python3.8\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Inkscape\lib\python3.8\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Program Files\Inkscape\lib\python3.8\http\client.py", line 944, in send
    self.connect()
  File "C:\Program Files\Inkscape\lib\python3.8\http\client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Program Files\Inkscape\lib\python3.8\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Inkscape\lib\python3.8\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\Inkscape\lib\python3.8\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
**ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)**
`

**Comment by angelobanse** [comment]
try `pip install --upgrade certifi`

**Comment by M-Colley** [comment]
Thanks for the quick reply but that did **not** resolve the issue.

**Comment by behrisch** [comment]
Do you have several python installations on this machine? Inkscape looks like an unusual location.

**Comment by M-Colley** [comment]
I did not, however, simply uninstalling and installing python 3.9 from scratch solved the issue. Thx for your answers!
