### ISSUE TITLE
struct.error when calling traci.start()

### ISSUE THREAD

**Issue by jiawei92** [eclipse/sumo#8327]
Sometimes I will get the error below when I call then traci.start() function, sometimes the code runs without error.

```
  File "/home/jiaweil9/Tasks/sim_env_ta.py", line 189, in initSUMO
  File "/usr/share/sumo/tools/traci/main.py", line 158, in start
    return init(sumoPort, numRetries, "localhost", label, sumoProcess)
  File "/usr/share/sumo/tools/traci/main.py", line 138, in init
    return getVersion()
  File "/usr/share/sumo/tools/traci/main.py", line 250, in getVersion
    return _connections[""].getVersion()
  File "/usr/share/sumo/tools/traci/connection.py", line 356, in getVersion
    result = self._sendCmd(command, None, None)
  File "/usr/share/sumo/tools/traci/connection.py", line 180, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 92, in _sendExact
    prefix = result.read("!BBB")
  File "/usr/share/sumo/tools/traci/storage.py", line 40, in read
    return struct.unpack(format, self._content[oldPos:self._pos])
struct.error: unpack requires a buffer of 3 bytes
```

**Comment by namdre** [comment]
make sure to call traci.close() before calling traci.start with the same (or default) label.

**Comment by jiawei92** [comment]
> make sure to call traci.close() before calling traci.start with the same (or default) label.

I do call `traci.close()` before calling `traci.start()`. I use SUMO API in a for loop:

```
for
    traci.start()
    do something
    traci.close()
```

Maybe my machine is slow, so that sometimes `traci.start()` will be conducted before traci is completely closed. The potential solution would be adding` time.sleep(1)` after `traci.close()`?

**Comment by behrisch** [comment]
Normally traci.close waits until the sumo process is finished so this should not happen. Can you share more of your code?

**Comment by jiawei92** [comment]
> Normally traci.close waits until the sumo process is finished so this should not happen. Can you share more of your code?

My original code is a little bit long, so I create a demo code that can also reproduce the error.
OS information: NAME="CentOS Linux" VERSION="7 (Core)"


```
import os
import sys

if 'SUMO_HOME' in os.environ:
    tools = os.path.join(os.environ['SUMO_HOME'], 'tools')
    sys.path.append(tools)
else:
    sys.exit("please declare environment variable 'SUMO_HOME'")

from sumolib import checkBinary  # noqa
import traci  # noqa


network_folder = r'../../../simulation/two_approaches'
network_filepath = os.path.join(network_folder, 'sim.net.xml')
route_filepath = os.path.join(network_folder, 'train-sim.rou.xml')

sumoBinary = checkBinary('sumo')

sumo_config = {'--net-file': network_filepath,
               '--step-length': '0.2',
               '--route-files': route_filepath,
               '--no-step-log': 'true'}

start_order = [sumoBinary]
for sumo_key, sumo_value in sumo_config.items():
    start_order.append(sumo_key)
    start_order.append(sumo_value)


def task():
    for _ in range(10000):
        traci.start(start_order)
        for _ in range(10): traci.simulationStep()
        traci.close()


if __name__ == '__main__':
    task()
    print('done')
```

The error message I got:

Error: tcpip::Socket::accept() Unable to create listening socket: Address already in use
Quitting (on error).
Traceback (most recent call last):
  File "test.py", line 45, in <module>
    task()
  File "test.py", line 39, in task
    traci.start(start_order)
  File "/usr/share/sumo/tools/traci/main.py", line 158, in start
    return init(sumoPort, numRetries, "localhost", label, sumoProcess)
  File "/usr/share/sumo/tools/traci/main.py", line 138, in init
    return getVersion()
  File "/usr/share/sumo/tools/traci/main.py", line 250, in getVersion
    return _connections[""].getVersion()
  File "/usr/share/sumo/tools/traci/connection.py", line 356, in getVersion
    result = self._sendCmd(command, None, None)
  File "/usr/share/sumo/tools/traci/connection.py", line 180, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 92, in _sendExact
    prefix = result.read("!BBB")
  File "/usr/share/sumo/tools/traci/storage.py", line 40, in read
    return struct.unpack(format, self._content[oldPos:self._pos])
struct.error: unpack requires a buffer of 3 bytes

**Comment by behrisch** [comment]
Which sumo version is this?

**Comment by jiawei92** [comment]
> Which sumo version is this?

version 1.8.0

By the way, as my operation system is CentOS and I cannot directly install SUMO on it, I install and run SUMO in a singularity (From: ubuntu:latest) using apt install.

**Comment by behrisch** [comment]
The relevant error is on the top
```
Error: tcpip::Socket::accept() Unable to create listening socket: Address already in use
```
So the socket is still blocked, although this should not happen as well. It might be that the OS is too slow in freeing it after we checked for a free port.

**Comment by behrisch** [comment]
I simplified the script a little to
```
import os
import sys
sys.path.append(os.path.join(os.environ["SUMO_HOME"], "tools"))
import traci

for _ in range(10000):
    traci.start(["sumo", "-n", "net.net.xml", "-r", "input_routes.rou.xml"])
    for __ in range(10): traci.simulationStep()
    traci.close()
```
which works here without a problem (so far, not all 10000 done yet). How often does the error occur?

**Comment by jiawei92** [comment]
> I simplified the script a little to
> 
> ```
> import os
> import sys
> sys.path.append(os.path.join(os.environ["SUMO_HOME"], "tools"))
> import traci
> 
> for _ in range(10000):
>     traci.start(["sumo", "-n", "net.net.xml", "-r", "input_routes.rou.xml"])
>     for __ in range(10): traci.simulationStep()
>     traci.close()
> ```
> 
> which works here without a problem (so far, not all 10000 done yet). How often does the error occur?

If I run the script many times, about 10% will encounter the error. I think the machine is very slow. If I run this script on another new laptop, it works without a problem. I temporarily put `traci.start()` under `try` to avoid program crash for now

```
while True:
    try:
        traci.start(start_order)
        break
    except:
        time.sleep(2)
```

**Comment by behrisch** [comment]
OK, can you try to add the following line in tools miscutils.py in the function getFreeSocketPort after `s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)`:
```
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
```

**Comment by behrisch** [comment]
By the way, you may be better off using [libsumo](https://sumo.dlr.de/docs/Libsumo.html) in your case.

**Comment by jiawei92** [comment]
> By the way, you may be better off using [libsumo](https://sumo.dlr.de/docs/Libsumo.html) in your case.

As I use SUMO in a singularity container, I cannot access and modify SUMO files in the singularity once it's created, so I cannot add any lines into miscutils.py
libsumo may be a good alternative. Thanks for your help.

**Comment by behrisch** [comment]
It might be useful to add SO_REUSEPORT when checking for a free socket but we need a good test case / machine first. Keeping the ticket open as a reminder.
