### ISSUE TITLE
Can `traci.load` work with multiple clients?

### ISSUE THREAD

**Issue by ramonfontes** [eclipse/sumo#8893]
Simulation freezes after running `loadState`

**Comment by namdre** [comment]
This should work. If you are using sumo-gui as the server you either have to include "--start" the sumo options or click the run button after calling traci.load.
If that doesn't solve your problem,
please try to create a minimal example for reproducing the freeze and attach it to this issue.

**Comment by ramonfontes** [comment]
Please consider the codes below:

```
# code1.py

import os
import sys
SUMO_HOME = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "..", "/usr/share/sumo")
sys.path.append(os.path.join(os.environ.get("SUMO_HOME", SUMO_HOME), "tools"))
import traci

command = 'sumo-gui -c "map.sumocfg" --num-clients 2 --remote-port 8813 \
          --time-to-teleport -1 --start --delay 100 &'

os.system(command)
traci.init()
traci.setOrder(0)

while True:
    print("before")
    traci.simulation.step()
    print("after")
```


```
# code2.py

import sys
import os
SUMO_HOME = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "..", "/usr/share/sumo")
sys.path.append(os.path.join(os.environ.get("SUMO_HOME", SUMO_HOME), "tools"))
import traci

PORT = 8813
ADDR = '127.0.0.1'
traci.init()  # port, numRetries, host
traci.setOrder(2)  # number can be anything as long as each client gets its own number

while True:
    traci.simulationStep()
    if float(traci.simulation.getTime()) > 50.0:
        traci.load(['-c', 'map.sumocfg', '--start', '--num-clients', '2', '--remote-port', '8813'])
```

I first run `code1.py` and it waits for `code2.py`.
```
python code1.py
```
```
python code2.py
```

> Here `sumo-gui` works perfectly until time == 50.0 

However, when `code2.py` calls `traci.load()` something wrong happens and `sumo-gui` freezes.

This is my `map.sumocfg`;

```
<?xml version="1.0" encoding="iso-8859-1"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.sf.net/xsd/sumoConfiguration.xsd">
    <input>
        <net-file value="map.net.xml"/>
        <route-files value="map.rou.xml"/>
        <additional-files value="map.poly.xml"/>
    </input>

    <output>
	<tripinfo-output value="maptripinfo.out.xml"/>
    </output>

    <time>
        <begin value="0"/>
        <end value="1000"/>
	<step-length value="0.1"/>
    </time>
    <report>
        <no-step-log value="true"/>
        <xml-validation value="never"/>
    </report>
    <traci_server>
	<processing>
		<time-to-teleport value="100"/>
	</processing>
         <remote-port value="8813"/>
    </traci_server>
</configuration>
```

**Comment by ramonfontes** [comment]
`code1` is simplified for reproducibility purposes. In fact, it has several instructions, for example, some that retrieve vehicle position, simulation time, etc. `code2` is necessary as I intend to restart the simulation based on some machine learning algorithms.

**Comment by behrisch** [comment]
Some questions concerning the code:

- What does this have to do with loadState?
- Is there a reason for setOrder(2) although you only have two clients?
- Did you try it without GUI?

**Comment by ramonfontes** [comment]
> What does this have to do with loadState?
I though I could mimic `load` with `loadState` but it didn't work either. I'm removing `loadState` from the issue title.

> Is there a reason for setOrder(2) although you only have two clients?
Nope. There is no special reason for that.

> Did you try it without GUI?
Yes, I tried without GUI and the result is the same. `code2.py` breaks when running `traci.simulationStep()`

The following error happens when I manually stop the simulation (by typing ctrl+c).

```
^CTraceback (most recent call last):
  File "c2.py", line 14, in <module>
    traci.simulationStep()
  File "/usr/share/sumo/tools/traci/main.py", line 227, in simulationStep
    return _connections[""].simulationStep(step)
  File "/usr/share/sumo/tools/traci/connection.py", line 308, in simulationStep
    result = self._sendCmd(tc.CMD_SIMSTEP, None, None, "D", step)
  File "/usr/share/sumo/tools/traci/connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 87, in _sendExact
    result = self._recvExact()
  File "/usr/share/sumo/tools/traci/connection.py", line 66, in _recvExact
    t = self._socket.recv(4 - len(result))
KeyboardInterrupt
```

**Comment by behrisch** [comment]
I am still not sure what happens here. I tried to set up our own test derived from https://github.com/eclipse/sumo/tree/master/tests/complex/traci/connection/multipleConnections/basic and it works

**Comment by ramonfontes** [comment]
I really appreciate your help @behrisch. I tried to give you the most simple code as possible with a few lines of code. It would be very important for us to have such a feature working.

I hope you can find the reason for that behavior.

**Comment by ramonfontes** [comment]
I just got the problem solved and the solution was kind of embarrassing. I just reversed the execution order of c1 and c2 and it worked (e.g. `traci.setOrder(0)` to `traci.setOrder(1)` and vice-versa)!

Three weeks resolved with only one line of code :(.

**Comment by namdre** [comment]
@behrisch any idea why the order of setOrder could have an impact?

**Comment by behrisch** [comment]
No, especially since the initial order seems like the logical one. We should investigate it.
