### ISSUE TITLE
sumolib.net.readNet error

### ISSUE THREAD

**Issue by Ohay-Angah** [eclipse/sumo#9470]
Does anyone have the str-bytes concat issue when reading a SUMO net file before?

When I run
```
net = sumolib.net.readNet(netFile)
```
It gives me the error below:

Traceback (most recent call last):
  File "D:\tools\SUMO\tools\sumolib\net\__init__.py", line 814, in readNet
    parse(gzip.open(filename), netreader)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\xml\sax\__init__.py", line 33, in parse
    parser.parse(source)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\xml\sax\xmlreader.py", line 123, in parse
    buffer = file.read(self._bufsize)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\gzip.py", line 292, in read
    return self._buffer.read(size)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\gzip.py", line 422, in _read_gzip_header
    magic = self._fp.read(2)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\gzip.py", line 95, in read
    return self._buffer[read:] + \
**TypeError: can't concat str to bytes**
python-BaseException
  
---
My SUMO is the latest released version: 17.08.2021
Python version is 3.8

**Comment by namdre** [comment]
No, we didn't have that yet. How did you solve your problem?

@behrisch: might it be a good idea to also catch TypeError in the try-parse-gzip attempt?

**Comment by Ohay-Angah** [comment]
@namdre I solved it after I realized I didn't input the file name (_"myNet.xml"_) but the `netFile` (`netFile = open("myNet.xml", "r")`) when I called the `sumolib` function.  I really appreciate your reply!
