### ISSUE TITLE
crash on taxi dispatch

### ISSUE THREAD

**Issue by namdre** [eclipse/sumo#9733]
Found in the saga_riyadh scenario.

likely cause:
- something goes wrong with the dispatch
- person is teleported: Warning: Teleporting person '8835311_8835312_4' from vehicle destination edge '72267547#9' to intended destination edge '-55217696#4'
- reservation is still in the system
- person is removed from the simulation
- dispatch crashes when accessing the person in the reservation:

```
#0  0x0000000000000000 in ?? ()
#1  0x0000000000800d1d in MSDispatch::remainingCapacity (this=0xe371270, taxi=0x218b07a0, res=0x3755d6e0) at /home/erdm_ja/scr1/sumoD/src/microsim/devices/MSDispatch.cpp:261
#2  0x00000000008060b7 in MSDispatch_Greedy::computeDispatch (this=0xe371270, now=84060000, fleet=std::vector of length 96, capacity 128 = {...})
    at /home/erdm_ja/scr1/sumoD/src/microsim/devices/MSDispatch_Greedy.cpp:72
#3  0x00000000007bbf44 in MSDevice_Taxi::triggerDispatch (currentTime=84060000) at /home/erdm_ja/scr1/sumoD/src/microsim/devices/MSDevice_Taxi.cpp:208
#4  0x00000000007c7f6c in StaticCommand<MSDevice_Taxi>::execute (this=0x13139be0, currentTime=84060000) at /home/erdm_ja/scr1/sumoD/src/utils/common/StaticCommand.h:88
#5  0x00000000005463d9 in MSEventControl::execute (this=0x1198320, execTime=84060000) at /home/erdm_ja/scr1/sumoD/src/microsim/MSEventControl.cpp:69
#6  0x000000000041d0bd in MSNet::simulationStep (this=0x11a2670) at /home/erdm_ja/scr1/sumoD/src/microsim/MSNet.cpp:690
#7  0x00000000004198bd in MSNet::simulate (this=0x11a2670, start=0, stop=86400000) at /home/erdm_ja/scr1/sumoD/src/microsim/MSNet.cpp:386
#8  0x0000000000415e0d in main (argc=3, argv=0x7fffffffdbf8) at /home/erdm_ja/scr1/sumoD/src/sumo_main.cpp:98
```

```
25 (gdb) p *res
  26 $4 = {id = "429", persons = std::set with 1 elements = {[0] = 0x375626b0}, reservationTime = 57731000, pickupTime = 57731000, from = 0x13577820, fromPos = 47.871910471509729, to = 0x11fe8f50,
  27   toPos = 191.27882862264678, group = "8835311_8835312_4", line = "taxi", recheck = 57731000, state = Reservation::NEW}
```

**Comment by namdre** [comment]
person enters the wrong vehicle

**Comment by namdre** [comment]
riyadh no longer crashes.
