### ISSUE TITLE
FatalTraCI Error when retrieving taxiReservations

### ISSUE THREAD

**Issue by AL3XG3** [eclipse/sumo#9805]
When running a simulation with the taxi device I get a _FatalTraCIError_ when trying to retrieve reservations that have already been picked up.  I'm calling traci every 45 seconds in simulation time. It works fine until I reach about 33 000 seconds simulation time. I have tested the reservations occuring around 32 000 - 33 000 at an early simulation time and it works perfectly fine.  At the same simulation time I also call `traci.person.getTaxiReservations(1)` right before, which always works as well. 

I also have another scenario which uses the same reservations and the same network (only more taxi vehicles). There the error also occurs, but not at the same time hence not for the same reservations. 

Generically speaking what could be the practical reasons for this occuring at this specific call after it worked for so long? What could be directly associated to it and how come, that the call `traci.person.getTaxiReservations(1)` works at the same time step? I'm quite confused by this error and debugging is pretty nervewracking when having to wait around 33 000 seconds for the error to occur. 

```
Traceback (most recent call last):
  File "C:\test\OrderManagement.py", line 153, in get_new_reservation_state
    picked_reservations = [res.id for res in traci.person.getTaxiReservations(8)]
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\_person.py", line 253, in getTaxiReservations
    answer = self._getCmd(tc.VAR_TAXI_RESERVATIONS, "", "i", onlyNew)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\domain.py", line 177, in _getCmd
    r = self._connection._sendCmd(self._cmdGetID, varID, objID, format, *values)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 181, in _sendCmd
    return self._sendExact()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\traci\connection.py", line 91, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
```
  
---

**SUMO-version: 1.11.0**

**operating system: Windows 10 64 Bit**

**Comment by namdre** [comment]
I suspect that you are hitting the same error that is also causing this crash: #9733 
The symptoms are quite similar insofar the error only occurs after a long simulation time.
(Which makes it hard to pin down the root cause)

**Comment by AL3XG3** [comment]
Thanks for your answer  @namdre 

I went through the latest commits on my project (since the error started occuring very suddenly with the project working fine for several days).  Strangely enough removing the _arrivalPos_ (recent commit) from the definition of reservations (person rides) made the error disappear again.  Do you see any causal connections there? From my perception it seems that it isn't associated to the issue you mentioned, since it's still the exact same simulation and reservations except for the _arrivalPos_.

**Comment by namdre** [comment]
Thanks for this piece of information!
I suspect that the error is connected to some kind of mismatch between the expected arrival position of rides and the actual arrival position of vehicles. Such a mismatch might cause a person to remain in the vehicle after the vehicle stops and thereby wreck the whole person plan.

**Comment by namdre** [comment]
I fixed a taxi-related crash just now. Please rebuild sumo (or download the pre-built version **tomorrow** at https://sumo.dlr.de/docs/Downloads.php#sumo_-_latest_development_version and check if it solves your crash as well.

**Comment by AL3XG3** [comment]
I've just tried it with different reservation data. Unfortunately, the error still gets thrown when using _arrivalPos_ inside of the reservation definitions.

**Comment by namdre** [comment]
Can you provide a test case for reproducing the crash? It would be great if you could reduce the input to be somewhat minimal (i.e. by iteratively removing half of the taxis and persons until the crash no longer occurs, then adding back the objects from the last removal)

**Comment by namdre** [comment]
@AL3XG3 Is there any possibility of providing test input? I'd really like to get this crash fixed before our upcoming release of version 1.12.0 scheduled for Jan 25th.

**Comment by AL3XG3** [comment]
> @AL3XG3 Is there any possibility of providing test input? I'd really like to get this crash fixed before our upcoming release of version 1.12.0 scheduled for Jan 25th.

@namdre Since the simulation scenario is part of a project with works of others and also part of a thesis, I am obliged to not distributing any code atm. 

I'll get back to you once I've consulted with the supervisor of my thesis.

**Comment by namdre** [comment]
There is no need to distribute code. Logging the issued traci commands is sufficient (https://sumo.dlr.de/docs/TraCI/Interfacing_TraCI_from_Python.html#generating_a_log_of_all_traci_commands)
If you can make it crash with a reduced network or reduced fleet, that would be even better.

**Comment by Haishanliu** [comment]
> Thanks for your answer @namdre
> 
> I went through the latest commits on my project (since the error started occuring very suddenly with the project working fine for several days). Strangely enough removing the _arrivalPos_ (recent commit) from the definition of reservations (person rides) made the error disappear again. Do you see any causal connections to this attribute? From my perception it seems that it isn't associated to the issue you mentioned, since it's still the exact same simulation and reservations except for the _arrivalPos_, only without the error.

Hi, I also encountered the same issue with the command traci.getTaxiReservation(0). The error code is also: traci.exceptions.FatalTraCIError: Connection already closed. The simulation time for this error to occur is somehow random“ 2280s, 9080s, 19860s”. Do you directly remove the arrival_pos from the reservation definition? If so, where will be the arrival position of the rider? Actually, my trip definition didn't specify the arival_pos. It was generated by SUMO when loaded.  

Thank you! I really appreciate your time and help.

**Comment by namdre** [comment]
@Haishanliu I suspect that yours is a separate issue even though it concerns the same method. Please open up a new ticket and give more details (preferably a reproducible input example).
