### ISSUE TITLE
osmWebWizard

### ISSUE THREAD

**Issue by tanzeelarubab** [eclipse/sumo#9873]
amjad@amjad-Inspiron-N4050:~$ cd sumo/tools
amjad@amjad-Inspiron-N4050:~/sumo/tools$ python osmWebWizard.py
Traceback (most recent call last):
  File "osmWebWizard.py", line 550, in <module>
    args.address, args.port, OSMImporterWebSocket)
  File "/home/amjad/sumo/tools/webWizard/SimpleWebSocketServer.py", line 595, in __init__
    self.serversocket.bind((host, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

i reset the path and execute command. but error occurs. please help

*If possible, upload an example that shows your problem.*

**SUMO-version:**
sumo Version 1.11.0

**operating system:**
Ubuntu 20.04.3 LTS

**Comment by namdre** [comment]
you may keep posting in #9871
