### ISSUE TITLE
encoding problems in osmTaxiStop

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9893]
````
tsc>%SUMO_HOME%\tools\import\osm\osmTaxiStop.py -s data\berlin_net\osm\berlin_net.osm.xml.gz -n scenario_templates\berlin_net\tmp_output\1_net.net.xml.gz
Traceback (most recent call last):
  File "C:\Users\behr_mi\Projekte\sumo\repos\sumo\tools\import\osm\osmTaxiStop.py", line 112, in <module>
    main(parseArgs())
  File "C:\Users\behr_mi\Projekte\sumo\repos\sumo\tools\import\osm\osmTaxiStop.py", line 66, in main
    for n in sumolib.xml.parse(options.osm_file, "node"):
  File "C:\Users\behr_mi\Projekte\sumo\repos\sumo\tools\sumolib\xml.py", line 253, in parse
    for _, parsenode in ET.iterparse(_open(xmlfile, encoding)):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\xml\etree\ElementTree.py", line 1224, in iterator
    data = source.read(16 * 1024)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 9967: character maps to <undefined>
````

**Comment by namdre** [comment]
The above commit breaks the osmWebWizard test via ptlines2flows.py on Ubuntu 20.4 and RHEL 7 with
```
Traceback (most recent call last):
  File "/scr1/sumo/tools/ptlines2flows.py", line 394, in <module>
    main(get_options())
  File "/scr1/sumo/tools/ptlines2flows.py", line 387, in main
    trpMap, stopNames = createTrips(options)
  File "/scr1/sumo/tools/ptlines2flows.py", line 150, in createTrips
    for stop in sumolib.output.parse(options.ptstops, 'busStop'):
  File "/home/erdm_ja/scr1/sumo/tools/sumolib/xml.py", line 253, in parse
    for _, parsenode in ET.iterparse(_open(xmlfile, encoding)):
  File "<string>", line 103, in next
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 2040: ordinal not in range(128)
```
