### ISSUE TITLE
netedit tests not running in nightly linux build

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#9972]
The log shows 
````
Traceback (most recent call last):
File "/usr/local/bin/texttest", line 46, in <module>
program.run()
...
File "/usr/local/lib/python3.8/dist-packages/texttestlib/default/virtualdisplay.py", line 227, in startWindowManager
wmProc = subprocess.Popen(command, preexec_fn=preexec_fn, stdin=open(
File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.8/subprocess.py", line 1639, in _execute_child
self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType                
````
This is probably a texttest bug but could also be a misconfiguration on our side (or both)

**Comment by behrisch** [comment]
The major problem seems to be hanging Xvfb and fluxbox instances on the test server. The only proper solution is probably #8085
