### ISSUE TITLE
execution error of OSM Web Wizard

### ISSUE THREAD

**Issue by Tim9765** [eclipse/sumo#9996]
Hi, when I run "python osmWebWizard.py" and want to click the green button "Generate Scenario", the sumo-gui does not automatically open up due to the following error which appears:

`Cannot create directory 'C:\Windows\system32\2022-01-19-20-23-50'
Building scenario in 'C:\Users\[User]\Sumo\2022-01-19-20-23-50'
Downloading map data
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 487, in build
    builder.build()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 192, in build
    osmGet.get(osmArgs)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 134, in get
    readCompressed(conn, url.path, '<bbox-query n="%s" s="%s" w="%s" e="%s"/>' %
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 45, in readCompressed
    conn.request("POST", "/" + urlpath, """
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

Recovering
Recovering
Recovering
Recovering
`

What could be the reason for this error? I've installed the Python version 3.10.2 and the Sumo version 1.11.0. 
Thanks for the help in advance!

**Comment by namdre** [comment]
see https://sumo.dlr.de/docs/FAQ.html#osmwebwizardpy_fails_to_generate_scenario_on_windows_10

please reopen if you still have problems.

**Comment by MoiGabriel** [comment]
I have the same problem. @Tim9765 can you help me with your fix? Or maybe some suggestions?

Cannot create directory 'C:\Windows\System32\2022-02-12-13-22-28'
Building scenario in 'C:\Users\gaby_\Sumo\2022-02-12-13-22-28'
Downloading map data
Traceback (most recent call last):
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 487, in build
    builder.build()
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmWebWizard.py", line 192, in build
    osmGet.get(osmArgs)
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 134, in get
    readCompressed(conn, url.path, '<bbox-query n="%s" s="%s" w="%s" e="%s"/>' %
  File "C:\Program Files (x86)\Eclipse\Sumo\tools\osmGet.py", line 45, in readCompressed
    conn.request("POST", "/" + urlpath, """
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\gaby_\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

Recovering
Recovering
Recovering
Recovering

**Comment by namdre** [comment]
did you try 'pip install certifi' ?

Am Sa., 12. Feb. 2022 um 12:24 Uhr schrieb MoiGabriel <
***@***.***>:
